### ISSUE TITLE
BOTs attacking when behind objects / buildings

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#10]
Don't know if there is anything that can be done but the bots are currently attacking anyone they can see within their viewing angle and distance, even if the player is behind objects/buildings.

For example, on Noshahr Canals they will fire at you from the opposite side of the containers even though there is no way they can hit you.

**Comment by Joe91** [comment]
Yes, this can happen some times. Thats because a bot cannot see at all and gets triggered very easy by a player. After that he just shoots for 5 seconds. In some wierd cases even longer even if he can't see you anymore. We are working on it, but its not the highest priority.
If you find out what exactly causes this, please let me know...

**Comment by SmartShots** [comment]
> Yes, this can happen some times. Thats because a bot cannot see at all and gets triggered very easy by a player. After that he just shoots for 5 seconds. In some wierd cases even longer even if he can't see you anymore. We are working on it, but its not the highest priority.
> If you find out what exactly causes this, please let me know...

I take it they are already not supposed to be trying to shoot at you through objects/buildings then? I presumed it was just like that because there wasn't any code to tell them that the object or building was there.

**Comment by Joe91** [comment]
They should only ne triggered if there is a clear view or if you are very Close. But after the trigger they cannot detect if they can see you or Not. But they should stop after a short time if not.

**Comment by SmartShots** [comment]
> They should only ne triggered if there is a clear view or if you are very Close. But after the trigger they cannot detect if they can see you or Not. But they should stop after a short time if not.
> Could you try if this is still the same with the new master?

I'm currently using the latest release - V1.2.0.0 - and have tested it some more. They do seem to be getting triggered sometimes when there is clearly no view of me. 

[See this example video](https://youtu.be/1m9k8E6fkeA)

**Comment by Joe91** [comment]
The trigger in the video is the parameter "distanceForDirectAttack". If you are close to the bot (by default 3 m) he will attack. You can set this to 0

**Comment by SmartShots** [comment]
> The trigger in the video is the parameter "distanceForDirectAttack". If you are close to the bot (by default 3 m) he will attack. You can set this to 0

I have it set to 1 in this case. I will change it to 0 and re-test.

**Comment by Joe91** [comment]
Should be improved now. Still raycasts aren't that reliable...
