### ISSUE TITLE
Class Based Head Aiming.

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#100]
### Requested feature

I would like to see the AimForHead feature improved. Rather than just a global true/false I would like to see individual class switches, like this:

AssaultAimForHead = true,
EngineerAimForHead = true,
SupportAimForHead = false,
ReconAimForHead = true,

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Rn the aiming is all just a workaround (that works quite well in most of the cases. Once VU enables bots to aim like players, this would be much easier to implement. But I will give it a try anyways...

**Comment by Joe91** [comment]
will be in the next version, is already on the master (separated in sniper and normal bots...

**Comment by SmartShots** [comment]
> will be in the next version, is already on the master (separated in sniper and normal bots...

Will you be adding the further separation for all classes?
