### ISSUE TITLE
Squad Perks for BOTs?

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#101]
### Enhancement

Is it possible for the BOTs to use the Squad Perks? If so then I would like to see them using them and using them correctly - i.e. a different perk for each BOT in a squad.

The most important perks are:

SQD COVR
SQD AMMO
SQD SPRNT
SQD SUPR

So it would be good if the BOTs would take SQD COVR if nobody in the SQD already has it, followed by SQD AMMO and then SQD SPRNT and then SQD SUPR.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by FlashHit** [comment]
It’s not possible atm afaik

**Comment by Joe91** [comment]
implemented in new dev-version
