### ISSUE TITLE
Bots getting stuck in tight spaces and then dying

### ISSUE THREAD

**Issue by beamthelaser** [Joe91/fun-bots#109]
### What happened?

Bots are getting stuck in tight playspaces such as staircases and small passages between buildings on certain maps like Operation Firestorm, Grand Bazaar, among others. When they get stuck, they tend to jump in place, melee or shoot their equipped weapons at walls for about ~10 seconds, then commit suicide.

### What was expected?

Bots should be able to move through tight spots like those mentioned previously without exhibiting the reported behaviour.

### Version

2.0.0.x (Pre-Releases)

### Server information

Windows 10
32 GB of RAM
i5-10700F @ 2.9 GHz (boosts to 4.8 GHz)
Running other mods, but none that should affect the behaviour of fun bots
Playing on and hosting the server on the same machine

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Yeah the bots commit suicide once they are stuck. They get stuck because of how the traces are and sometimes because they jump over obstacles while attacking. This can be disables in the Config.lua (JumpWhileShooting).
The other option is to improve the traces and this is up to everyone...
