### ISSUE TITLE
BOT Spawn on player join?

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#11]
Is there any chance you could add an option to have another [x] amount of BOTs spawn when a player joins the server? up to the MAX_NUMBER_OF_BOTS?

You'd need an option to enable it and a setting for how many to spawn when a player joins.

A question whilst I am thinking about it - once the server is full do the BOTs take up slots that will stop more players joining? ...or do they get kicked?

**Comment by Joe91** [comment]
Good idea. I will implement it.
Top the server: I think Bots Take a normal slot, so the server is just full at some time. They do not get kicked,

**Comment by SmartShots** [comment]
> Good idea. I will implement it.
> Top the server: I think Bots Take a normal slot, so the server is just full at some time. They do not get kicked,

Excellent! Look forward to that!

With regards to the full server and bots not getting kicked - I'll raise another issue about it.

**Comment by Joe91** [comment]
Would you mind to test this new feature? I created a new brach for it, but am not able to test it right now...
Branch is called: feature_auto_amount_increase.
Regarding the full server: Could you test this as well? I'm really not shure how bots count exactly...

**Comment by Bizarrus** [comment]
@Joe91 did the `Player:Authenticated` event will not triggered? Otherwise use the [RequestJoin-Hook](https://docs.veniceunleashed.net/vext/ref/server/hook/player_requestjoin/)

**Comment by Joe91** [comment]
what do you mean? I alreade use the "Player:Joining" hook for this.

**Comment by Bizarrus** [comment]
>  I think Bots Take a normal slot, so the server is just full at some time. They do not get kicked

If the server is full of bots and a player want to join, with these hooks, you can check and kick a bot to get a free slot.

**Comment by Joe91** [comment]
Ah okay. I already tested it, but none of the hooks / events gets fired if the server is full. So the only way will be to keep always one slot free...
