### ISSUE TITLE
Better bots reaction when detect an enemy.

### ISSUE THREAD

**Issue by ThaigoLOCAO** [Joe91/fun-bots#112]
### Enhancement

When the bots find an enemy basically they start to shoot in it and then have two different reactions, the first one is shooting while walk in the direction of the enemy, and the second one is when it get too close of the enemy and it crouch. 
My idea consist in make a better reaction of the bots, for example when they detect an enemy they could start to shoot and then walk to left and right to evitate the enemy fire, another one for example is they walk back, or maybe walk diagonally as much foward and backward.
The requirement to a bot do a diferent reaction could be probability, so if we have 4 different reaction right, left, backward and forward, we should have 25% of chance to it do one of them.
And if we have 8 different reactions right, left, backward, forward, diagonally to forward and left, diagonally to forward and right, diagonally to backward and left and diagonally to backward and right, so we should have 12.5% of chance of bots make one of them.

I hope that my text it's understandable.

I don't know if is possible to add it to the mod, but it would let the bots much more realistic.

You are performing mine dream, and the dream of a lot of people around the world, so the only thing I can say is thank you so much :)

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Thank you for your idea and the feedback!
Since the bots can't determine what's in their environment I've chosen this simple behavior. The problem with other solutions could be, that the bots walk behind obstacles and therefore are not able to shoot ath others anymore.
But I will have a look if I can find a compromise...
