### ISSUE TITLE
Allow bots in the squad of a player to respawn on player

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#113]
### Requested feature

Allow bots, when respawing to respawn on a squad player if the player is the nearest near an objective.

**Example:**

- If the bot wants to target flag A and the nearest respawn spawn point is DEPLOY (A <-> DEPLOY = 300 meters) and SQUAD MEMBER A is 120 meters from flag A, the bot wants to respawn on that squad member.
- If the bot wants to target A but DEPLOY is closer, they still want to respawn on deploy.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Since a player can be far away from the next path of a bot and a search would be really expensive in cpu load I would suggest to just enable bots to spawn on other Squad-Mates (Bots). What do you think about that?

**Comment by Firjens** [comment]
> Since a player can be far away from the next path of a bot and a search would be really expensive in cpu load I would suggest to just enable bots to spawn on other Squad-Mates (Bots). What do you think about that?

That's even better.
