### ISSUE TITLE
Allow bots to respawn in friendly squad vehicles

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#115]
### Enhancement

Allow bots to respawn in vehicles of people who are in their own squad as a passenger.

- If John is driving a T90 (battle tank, 3 spaces) and there is no one else in there. And BOT_Arnold, who is in John's squad has to respawn, there is a small chance that he will respawn in John's T90 as a gunner.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
This is a little hard since I already tried to fire this spawn-event for vehicles and failed. Maybe one day, but not in the next few versions...

**Comment by Joe91** [comment]
I finaly added this feature on the dev-branch :-)
Do you want to check if it works the way you intended?

**Comment by Joe91** [comment]
Just reopen it if there is still an issue...
