### ISSUE TITLE
Probability that bots exit their vehicle when it's on fire or extremely low HP

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#116]
### Enhancement

There should be a large chance that bots who are driving in a vehicle, which is nearly destroyed ( < 5 HP?) that they exit the vehicle to prevent from dying. This should not always be the case, some bots should refuse to abandon ship.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Good idea. I will have to add the ability for the infantery to use the vehicle-paths and avoid them if there is a normal path as well. But this should be doable...

**Comment by Firjens** [comment]
What if infantry go through vehicle paths to the nearest infantry path?

**Comment by Joe91** [comment]
Some preparation is already done. When I extract the heath-information it should work very soon.

**Comment by Joe91** [comment]
The health-information is only absolute yet. Haven't found a relativ healph yet...

**Comment by Joe91** [comment]
added in new dev-version. Stil WIP
