### ISSUE TITLE
Allow bots to use static vehicles (TOW, Phalanx CWIS, etc.)

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#117]
### Requested feature

Bots should be able to enter in stationary vehicles when the situation calls for.

- A bot should be able to enter nearby anti-air stations, such as the Phalanx (The BRRRRRRRRRRRRR machine which shoots ∞ bullets per microsecond) and attempt to target the aircraft. The bot should exit the vehicle once the aircraft is out of range, destroyed of when the bot has had enough of it.
- A bot should be able to use BGM-71 TOW and other anti vehicles weaponry when a land vehicle is nearby and they do not have any anti vehicle weaponry and try to shoot the vehicle.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Hard to spawn them directly but with paths to that this could already be possible... But not tested yet...

**Comment by Firjens** [comment]
Any updates on this? @Joe91 is it planned for a release soon or a long-time goal? Anything that VU has to implement before being able to do this?

**Comment by Firjens** [comment]
Fixed in aaaf742cb3e82db677e94fa038fd4758d8a92122
