### ISSUE TITLE
Balance players appropriately on both teams

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#120]
### Requested feature

A configuration option to balance players on both teams.

**Example:**
- I have `DoBalanceTeam: true` in my configuration file
- I have `BalanceTeam: 0.5`, I want 50% of all players to be on team A and 50% on team B

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by SmartShots** [comment]
Is this right, you're looking to balance players, not bots?  If so then can you make sure it can be disabled. I use the Procon Multibalancer plugin to balance my servers players and this would likely cause problems with it.

**Comment by Firjens** [comment]
> Is this right, you're looking to balance players, not bots? If so then can you make sure it can be disabled. I use the Procon Multibalancer plugin to balance my servers players and this would likely cause problems with it.

Updated the issue.
