### ISSUE TITLE
Downscale rendering in waypoint menu if low FPS

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#121]
### Enhancement

When having a low FPS, the amount of rendering going on in the F12 waypoint menu should be lowered.

- When above 100 FPS, no downscaling should be done.
- Between 20-80 FPS, downscaling should be done

**Notes:**
https://discord.com/channels/862736286774198322/862738956456951809/862810642297651220
https://docs.veniceunleashed.net/vext/ref/fb/frameratehistogramperformanceevent/
https://docs.veniceunleashed.net/vext/ref/fb/timingviewsettings/

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
in dev working. No reduction needed anymore...
