### ISSUE TITLE
BOTs looking up when walking.

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#125]
### What happened?

Quite often I see BOTs just walking along but looking up in the air.

I mentioned it to Joe and he thinks it could be that they are not getting reset after throwing or trying to throw a grenade. Raising this issue so Joe can look at it later when he has time.

### What was expected?

BOTs walking normally looking straight ahead, in front of themselves.

### Version

2.1.0 (stable release)

### Server information

N/A

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
should be fixed now...
