### ISSUE TITLE
Bots should repair nearby allied vehicles

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#127]
### Requested feature

When a bot is nearby an allied vehicle, they should repair it if they have the appropriate tools for it and when the situation calls for it (not getting shot at, etc.).

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Wait for server-sided raycasts

**Comment by Joe91** [comment]
Repair is implemented as bot-command. Autodetection might cause lots of additional calculations...

**Comment by Joe91** [comment]
I think the Bot-Command fulfills this task good enough. Will close this if you are okay with that. I don't think I will add an automatic scan in general for this feature...
