### ISSUE TITLE
Balance bots based on each team's average score

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#128]
### Requested feature

An option to balance the amount of bots on each team based on the average score of each team, this scoring should include bots and players and only occur after there are enough players online to be able to balance them out better.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by SmartShots** [comment]
I already do this by combining the Procon Multibalancer plugin alongside funbots.

Funbots balances the BOTs between teams and Multibalancer balances the players and does so based on player k/d, score, team score, etc. It has a lot of options on how you want to balance.

As that's already available do you really want to spend dev time adding the same feature to funbots itself? I don't think funbots needs to do everything itself.
