### ISSUE TITLE
Friendly BOTs still fire at you sometimes.

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#13]
If I add BOTs to the same team as me they will still decide to shoot at me sometimes. Some of the time they ignore me but then all of a sudden they start attacking me as if I am an enemy.

Once they start attacking me they continue to do so.

With friendly fire turned off their bullets don't do any damage but if I get close enough and they melee me then that does do damage, even with friendly fire turned off. 

[See this video example](https://youtu.be/9yknMbQqtO0)

**Comment by Bizarrus** [comment]
I think, here is missing a Team-Check.

**Comment by Joe91** [comment]
No, the teams are checked correctly. But I think the client and the sever are out of sync on the teams. I will try a new approach to this.
