### ISSUE TITLE
BOTs not attacking me when they should.

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#130]
### What happened?

See video: [https://youtu.be/z25ED5LYAPU](https://youtu.be/z25ED5LYAPU)

Recon BOTs are not attacking me most of the time when they can clearly see me.

I have tested this with the other classes and Support does the same thing but both Assault and Engineer classes attack me fine with no issues. So this issue only affects Recon and Support classes.

### What was expected?

BOTs shooting me.

### Version

2.2.0-dev (development builds)

[UPDATE: I just tested it and this also happens in the stable Full Release 2.1.0]

[UPDATE: It also happens in the stable Release V2.0.0.6.}

### Server information

MOBO : AsRock Extreme6 Z77
CPU : Intel i5 3590k @ 4.6 Ghz
RAM : 16GB 3200Mhz Corsair Vengeance
GPU : EVGA GTX 1060 SC 6GB
CASE : Cooler Master HAF XB
COOLING : Air cooled
POWER : Corsair Gold AX850
MONITORS : 1 x ASUS 165Hz 1080p 27", 2 x BenQ 60Hz 1080p 27"
HDD : Samsung 500GB NVME SSD, WD Caviar Black 4TB
OS : Windows 10 Pro

Peripherals:
KEYBOARD : Razer BlackWidow Ultimate
MOUSE : Razer Deathadder v2 Pro
KEYPAD : Razer Tartarus v2
MOUSEPAD : Razer Goliathus Speed Large
HEADSET : Razer BlackShark v2 Pro

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by SmartShots** [comment]
If you want to test it this is the config I am using.
[Config.zip](https://github.com/Joe91/fun-bots/files/6794108/Config.zip)

**Comment by Joe91** [comment]
I can't reproduce this here. But can you try if it still happens if you modify this line:
https://github.com/Joe91/fun-bots/blob/master/ext/Server/Bot.lua#L1980
Just set it to "false" instead of "true".
This would help me a lot to find out what causes this...

**Comment by Joe91** [comment]
It is cause by your expert-Settings. Just use the normal timings in there...

**Comment by SmartShots** [comment]
I've narrowed it down to the BotMinTimeShootAtPlayer and BotFireModeDuration settings that are causing this. They affect it in different ways though but both can cause this if set too low.

Through my testing I have come up with these as minimum values:

BotMinTimeShootAtPlayer = 1.5,
BotFireModeDuration = 3.0,

If you go below those numbers, on either setting, then you start have problems. Maybe add these in the config notes as recommended minimums?
