### ISSUE TITLE
Verticle FOV for Shooting?

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#131]
### Enhancement

We have the FovForShooting but this doesn't seem to affect the verticle axis. For example, if I am up on top of a container and an enemy bot walks by on the ground next to the container, directly next to me but well below me, so I am looking directly down on them then they shouldn't be able to automatically see me and start firing at me.

Can we get a VerticleFovForShooting?

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
quite expensive to do these extra checks, but not that hard to implement. I will have a look. But not with a high priority yet...
