### ISSUE TITLE
Bot's completely ignore some players/bots unless shot

### ISSUE THREAD

**Issue by lywit** [Joe91/fun-bots#143]
### What happened?

It seems that bots do not consistently detect players and bots, they completely ignore some, they detect others normally.

This issue has happened since before the 2.0 release. I assumed this was due to custom settings, Joe thought it was due to too many raycasts or detected distances that were too high. It still happens to me using the default config with 32-48 bots.

I tried decreasing detection distances and the amount of raycast cycles, these did not appear to make a difference.

Examples:
https://imgur.com/a/1xOyyJ0

### What was expected?

The bots should detect players and other bots consistently.

### Version

2.2.0-dev (development builds)

### Server information

I am running on Windows Server 2019 my server has 32GB of RAM and it's running on an I-9900K.

Funbots is running alongside a couple other mods but I have tested this issue in isolation and it happens regardless of other mods.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
It could really be a client issue. Its really hard to reproduce. Once I am able to I can investigate this further...

**Comment by Joe91** [comment]
fixed in -dev4
