### ISSUE TITLE
Prevent bots from spawning on bots that are in the stuck behaviour

### ISSUE THREAD

**Issue by lywit** [Joe91/fun-bots#145]
### Enhancement

Bots will currently spawn on bots that are stuck, causing them to be stuck too. For example, bots will sometimes cause a traffic jam in doorways and get in their stuck behavior (Shooting, jumping, knifing, etc.) When a bot is in this behavior it shouldn't be eligible as a spawn point for the bots in their squad.

### Use case

This would cause less bots to be stuck and will reduce 'traffic jams' in doorways.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Try again with the new dev-buid
