### ISSUE TITLE
Bots won't spawn

### ISSUE THREAD

**Issue by Malarkey27** [Joe91/fun-bots#146]
### What happened?

Hello,

After setting my own server and test it with FunBots my first test was a success, bots are spawning et doing objectives nice !

But now bots doesn't spawn any more, i change version of Funbots, try to lunch with other gamemode and maps and nothing happen even witch the Funbots.permission in PRoCon.

### How can we reproduce and test it?

![vu](https://user-images.githubusercontent.com/87870135/126813185-da10488b-7f6f-40c4-9125-8d1af566cbdf.png)

### What was expected?

![vu](https://user-images.githubusercontent.com/87870135/126813042-5f019e17-69e0-4942-bd67-27819002f5da.png)

### Version

2.2.0-RC1

### Server information (if applicable)

Laptop
Windows 10
Ryzen 7 3750h
RTX 2060
16Go ram
SSD 500Go
HDD 1To

Venice EXT 1.1.0
fun-bots-2.2.0-dev5

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.
- [X] I have tested and reproduced this bug with the default fun-bots configuration file.

**Comment by Firjens** [comment]
How can we reproduce this? What map and gamemode are you playing on? Not all gamemodes and maps are currently supported.

**Comment by Joe91** [comment]
If I start the server with conqutest small on metro everything works just fine.
Can you blease check if this is also the case with -dev5? Or what gamemode or map are you having problems with?

**Comment by Malarkey27** [comment]
I just use the map associeated with gamemode in the maplist in fun-bots-2.2.0-RC1 case.
I have retry with fun-bots-2.2.0-RC1 with a new server.key with MP_018 ConquestSmall0 1 and nothing happen no bots.

I have try with a other PC and all work fine idk why with this PC it's broken.

**Comment by Malarkey27** [comment]
i followed this guide : https://vicadia.com/how-to-play-battlefield-3-with-bots-complete-guide/

**Comment by Joe91** [comment]
are you using a clean version of fun-bots or have you modified some settings?

**Comment by Joe91** [comment]
On what maps do the bots spawn? Can you maybe modify the Debug.lua and set this "printall = true" and share your server-console when you joined the server?

**Comment by Joe91** [comment]
Since I can't reproduce this I need more information to find out whats wrong with your setup...
You can also use the latest -dev verseion of the mod, but I think this won't change anything...

**Comment by Malarkey27** [comment]
Thank you for supply.

I use a clean Funbots, i have downloaded the lastest of FunBots 2.2.0-RC1.

**Comment by Malarkey27** [comment]
the bots spawn on any maps.. i try metro, gulf of oman, karg, Scrapmetal and nothing

**Comment by Malarkey27** [comment]
![vu](https://user-images.githubusercontent.com/87870135/126912165-82fffa16-a467-4070-b173-e75787d9426e.png)

**Comment by Malarkey27** [comment]
i think this is the problem right ?

**Comment by Joe91** [comment]
Is the mod.db file in the fun-bots-folder and how big is the File?

**Comment by Malarkey27** [comment]
yes 14 860 KB

**Comment by Firjens** [comment]
Unable to replicate, please provide more information on how to replicate.

**Comment by Malarkey27** [comment]
The mod work fine on my desktop but for my laptop nothing happen with the same settings.
Maybe the CPU is at issue, Ryzen 7 3750h 4 core 8 threads 2.3GHz (boost 4.0GHz)

You can close.

**Comment by Firjens** [comment]
Unable to replicate.

**Comment by Joe91** [comment]
Do you use the zipped Version of VU?

**Comment by Joe91** [comment]
What is the difference between your Desktop and your Laptop?

**Comment by Malarkey27** [comment]
No i installed it with the .exe

**Comment by Malarkey27** [comment]
The Spec :

Laptop :    Windows 10 
                 Ryzen 7 3750h
                 RTX 2060
                 16Go ram
                 NVMe 500Go   (VU Directory)
                 HDD 1To          (BF3 Directory)

Desktop : Windows 10     (20H2)
                 i9 10850K
                 RTX 3070         (NVidia Driver 471.41)
                 32Go RAM
                 NVMe 256Go   (VU Directory)
                 SSD Sata 2To    (BF3 Directory)
                 HDD 2To

**Comment by Malarkey27** [comment]
I will try this week end to reinstall Origins, BF3, VU and funbots on the laptop
