### ISSUE TITLE
Can't spawning the bots

### ISSUE THREAD

**Issue by LucasDotz** [Joe91/fun-bots#149]
### What happened?

I follow all instructions to install, get a lastest version 2.2.0, set permission *, a access the menu, but bots dont spawning, i put f2, increse numbers and nothing happens, i don't what i do.

### How can we reproduce and test it?

I set the permissions and access the bots menu, put f2 and a can't spawning the bots.

### What was expected?

bots spawning, and when i start the server, any bots spawning, i dont know if was a expected behavior, but a seeing in some videos.

### Version

2.2.0-RC1

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.
- [X] I have tested and reproduced this bug with the default fun-bots configuration file.

**Comment by LucasDotz** [comment]
sorry, for my english.

**Comment by Joe91** [comment]
Hi,
What map and gamemode are you using?

**Comment by LucasDotz** [comment]
Is the game mode not supported.

**Comment by Firjens** [comment]
See https://github.com/Joe91/fun-bots/wiki/Supported-maps for a list of all supported maps.
