### ISSUE TITLE
Add a function to walk randomly on the waypoint

### ISSUE THREAD

**Issue by Daniel-from-Germany** [Joe91/fun-bots#151]
### Requested feature

All Bots running exactly on the same route/waypoint, so its not a real movement, maybe u can implement a little randomizes running behavior

### Use case

So that the bots look real

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
This is already implemented. Bots pick a random path to a waypoint.
