### ISSUE TITLE
Add a Enable/Disable function for the the kick function by detect the player with the Botnamemark (BOT_)

### ISSUE THREAD

**Issue by Daniel-from-Germany** [Joe91/fun-bots#152]
### Requested feature

Modify the function "self.KickPlayers", to enable/disable it by remove the (BOT_) mark.
Currently you are kicked by the server if you remove the mark in the name of the bots (BOT_)

### Use case

There is more real feeling if you dont read how kill you by mixed players and bots.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Removing the Bot-Tag or using Bot-Tags as players comes with many other issues. Thats why this should not be done ;-)
But I can have a look if I can rewrite the core Bot-Handling to remove the Bot-Tag.

**Comment by Joe91** [comment]
Added Registry option for that on the latest commit of the dev-branch. You can test it out if you want...
