### ISSUE TITLE
Let the bots play further by no real player is connected on the server

### ISSUE THREAD

**Issue by Daniel-from-Germany** [Joe91/fun-bots#153]
### Requested feature

Modify the function “BotSpawner:UpdateBotAmountAndTeam”, to enable/disable s_PlayerCount for kick bots by zero players AND there play further.

### Use case

So the server looks like permanently are playable and full, the map rotation to be continued

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
I'll mark this as a low priority. Bots do not change the visible player count at all and this will just increase power consumption of the server it's running on. For continues map rotation you should create a new mod for just that purpose as it's not in the scope of fun-bots.

**Comment by Firjens** [comment]
This is not planned. Bots do not need to stay online when there are no other players.
