### ISSUE TITLE
Bot stuck on his old waypoint by gamemode rush

### ISSUE THREAD

**Issue by Daniel-from-Germany** [Joe91/fun-bots#154]
### What happened?

Sometimes Bots cant release here old waypoint if you play rush an there “stuck” in it

### How can we reproduce and test it?

Play MP_Subway RushLarge0 with 32+ bots (16+ each side)

### What was expected?

The bots walk around his old waypoint and there dont fight with the rest of the bot, you must teamkill it to respawn on the new waypoint

### Version

2.2.0-RC1

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.
- [X] I have tested and reproduced this bug with the default fun-bots configuration file.

**Comment by Firjens** [comment]
What waypoint and old waypoint? Coordinates? Which location?
