### ISSUE TITLE
Dynamic difficulty for a bot based on the skilll of the other team

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#158]
### Requested feature

A dynamic bot skill system that will adapt their spread, damage, etc. based on the skill of the opposite team, this should be configurable.

### Use case

When team A has 2 players, and team B has 6 players.

Team B skill (who fight against A) should have their skill adapted (damage, etc.) based on the skills of the two team A players and vice-versa

A configuration option to allow this to be customised should be added (it should be made easy with just a couple of options to prevent people from breaking their own head over it)

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Sj0erd** [comment]
Another option is to add a 'Mixed' mode. Here you can, for example, when you play 8 vs 8, 5 of the bots are 'Easy', 2 bots 'Medium' and 1 bot 'Expert'.

This way it is challenging for everyone to play against the bots, even the veterans among us.
