### ISSUE TITLE
When the driver communicates "Bail Out" (Via Q), bots should exit vehicle

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#161]
### Enhancement

When the driver of a vehicle uses the "bail out" command using Q. Bots should exit the vehicle.

### Use case

When a driver wants to a real person to enter the vehicle but a bot is already in it, this allows the driver to make room for a real player to enter in the vehicle.

Additionally the moment the bots are in an useless position such as the commander position in a tank, this allows them to leave and resume infantry combat.

Bots should pathway using vehicle paths to the nearest infantry path.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Sj0erd** [comment]
I remember from Battlefield 2, when you were in a vehicle with a bot that you could always spam 'F1' or 'F2' (or F3, F4, F5 etc.) and then take that spot. 

Or if you were a real player, you could press 'E' a lot and then take the bot's place if a vehicle was full.

**Comment by Joe91** [comment]
Now possible with the LEFT-ALT bot-menu...
