### ISSUE TITLE
Fetch traces from external API end-point

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#162]
Fetch bot infantry and vehicle traces for an external API-end point of the fun-bots server.

Each time the server starts, it makes a call to a specific API point and checks if there are new traces available (in a JSON format).
The client compares them with their current traces in the database (a timestamp has to be stored when it was last updated on the client and on the end-point).
If there are new traces available for a map, the client flushes their local database per map and redownloads them from the API end-point and stores them in the database.

This change will prevent user's mod.db from being modified when a new update is released, as this causes their stored data to be lost (permissions, settings later on... etc). The mod.db should no longer be distributed in the repository.

A system to submit traces directly should be added on the API end-point. Maybe using a second repository fo Github, or a MySQL database with a control panel?

### Configuration options:
- Check for new traces (default true) - when true, it should allow the server to contact the external API end-point. 

### Registry options:
- URL to external end-point

**Comment by Firjens** [comment]
**Issue:** Database operations are really slow, writing to the database can take more than 10 seconds. This is time we don't have. How can this be resolved?

Is the database async so it can write without blocking the main thread? Then upon a first installation it has to take 30 seconds to install itself, which is fine as it'll only happen once per installation. The database is not async, but maybe VU can make it async?

If we can't write to the database fast enough and we don't want to make a server take an hour to start up, what do we do? Do we want to keep it in memory? Most likely not due to the size of the traces.

Another issue is when the server is unavailable, we can't purely rely on the external server to get our traces. How do people submit or change traces?

**Comment by Sj0erd** [comment]
Do you have to want this? Can't we just have an auto-updater that immediately fetches the latest dev branch from GitHub or a production release?

**Comment by Firjens** [comment]
> Do you have to want this? Can't we just have an auto-updater that immediately fetches the latest dev branch from GitHub or a production release?

We cannot write to files, it's not possible.
