### ISSUE TITLE
Priority list for bug fix and new new feature

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#165]
### Enhancement

Priority
-Fix a problem where sometimes other bot in-vehicle don't shot other bot in the vehicle.
-When a bot in a land vehicle try to climb and fails the next try it should sprint for a few seconds to have enough power to climb.
-Dead bot should be able to spawn in your vehicle or another bot vehicle in order to be a gunner and make the vehicle a bit more deadly.
-Add a transport option for land path, example "if bot on jeep/quad or boat" once rich the end of the path they should exit the vehicle.
this feature will improve the map flow since some maps is really big especially on CQL so make bot use transport vehicle this will make them move around the map faster. (i will do the path job once this feature is available)
-Bot in the vehicle should have more BotKillBotUpdateCheck in order to make the bot in the vehicle a bit stronger and have better vision on an enemy, this will also make the bot drive less and shoot less drive less chance to get stuck.

Extra but not priority atm
-bot should be able to exit a vehicle while is driving if the vehicle is disabled or low HP like 20-25, and if he has a repair tool it should repair the vehicle and then go back in if they don't have the repair tool they should just exit and run away try to find a path.
-bot in vehicles should be able to use secondary guns such as .50 cal on tank/lav or Heatseekers on AA.
-Add a dedicated option "BotDirectAttack"  only for AA  with a default range of 100-120 meters only for players in air vehicles.
-Improve Vehicle handling while stuck, they atm get stuck pretty easily however i know this is not an easy task to fix since the bot have no clue what is around him, anyway i noticed that they run back turn a bit and then go forward and try again, this is perfect but "from my perspective" they should turn a little bit more and also use the sprint option just like i mentioned before. another bot

### Use case

better gameplay experience 

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
Please split them up in seperate issues.
