### ISSUE TITLE
Better hill climbing for vehicle 

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#167]
### Requested feature

When a bot in a land vehicle tries to climb and fail the next try it should sprint for a few seconds to have enough power to climb.

### Use case

As I already said above this feature should improve hill climbing in vehicles.

this issue can be experienced in the maps where vehicle paths is supported.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
Fixed in https://github.com/Joe91/fun-bots/commit/79e96b98141e4fd2080fce73808583888a4c4208
