### ISSUE TITLE
Bot with RPG get too close to enemy vehicle

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#168]
### Requested feature

If a bot in a vehicle get shot from an RPG they should start run a bit backward also the bot with RPG should have a limited range to walk so he can't get too close 

### Use case

this issue can be experienced in all maps where land vehicles are supported.

the issue happen when infantry bot with RPG start walking towards the land vehicle 

What happens when the RPG bot gets too close to the Vehicle?

Bots in the vehicle have no angle to shoot back ( the above implementation should fix it )

You kinda can fix this by enabling BotCanKillHimself: True it in the Config.lua  but the problem is still there
the bot with RPG should not walk towards the vehicle in any case.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
added on dev-branch
