### ISSUE TITLE
Exit vehicle option for Land path

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#169]
### Requested feature

Add an "Exit vehicle" option to apply at the end of the land path.

### Use case

This feature can be used for transport land paths.

For example, "if bot on jeep/quad or boat" rich the end of the path they should exit the vehicle.

the land paths should be close or linked to the infantry path so once the bot exit the vehicle they can find the infantry path without getting lost.

this feature will make the gameplay fast and feel more realistic, having fast transport vehicle capturing flag located far away from the middle map example all Conquest Large maps.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Feature added on dev-Branch
