### ISSUE TITLE
Limited vertical fov for Tank and Lav ONLY

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#171]
### Requested feature

A separate setting "MAX Vertical FOV"  should be implemented in the config.lua for LAV and Tank ONLY.

### Use case

The Vertical fov settings can limit the vertical fov from the vehicle driven by bot
this feature is already implemented however extra Vertical FOV settings should be implemented only for LAV and TANK
excluding AA.

This should fix the issue where TANK or LAV get stuck in a loop trying to shoot you when you fly in a helicopter or jet, the logic behind this should limit the Vertical fov only for the mentioned vehicle since the turret cant point that high like the AA.

the final result should be if Tank or LAV starts aiming at you they should skip aiming if you fly too high outside his turret range.

the final settings should be something like this:

MaxVerticalFovLandVehicle: 60 or lower "this should be tested"
MaxVerticalFOVAA: 90 "AA don't have turret limit".

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
FOV Vertial is currently only used for non-AA Vehicles.
Maybe I should add a new category in the settings...
