### ISSUE TITLE
Bot in vehicle use secondary weapons

### ISSUE THREAD

**Issue by Gemini899** [Joe91/fun-bots#172]
### Requested feature

Bot driving vehicles should be able to use secondary weapons if available.

### Use case

Atm they only use primary weapons such as tank shell "if the bot is in the tank", 25mm "if the bot is in LAV", 20mm "if the bot is in AA".
This works fine as basic driving behavior but i think there is space for improvement; for example:

1# Scenario: Bot in Tank uses his Shell while reloading the next one they should use .50 cal "only vs infantry" then swap back on the Shell when is reloaded.

2# Scenario: Bot in AA use 20mm vs infantry and Air vehicle, but he should alternate the primary with the secondary "Heatseekers" only vs Air Vehicle if they are in range.

3# Scenario: Bot in LAV uses 25mm vs infantry and enemy vehicles, they should use the .50 cal while reloading just like the tank behavior.

With this implementation, the bots can use the full potential of the vehicle they are driving making the experience feel more realistic as well and be more effective in what they are doing.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Started implementing it, but it seems that the bots are not able to switch the weapons in the vehicle. At least I tried, but the just don't switch.
Maybe someone can help there. Maybe this is not possible with VU atm...

**Comment by Joe91** [comment]
initial implementation on dev branch. Still a lot to do, but working as a start
