### ISSUE TITLE
Auto update - Remove devbuilds from config and fetch based on downloaded build

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#175]
### Enhancement

When the mod is checking for updates, it should either check for full release, release candidates or development builds based on the downloaded build. If the build is a release candidate it should check for newer releases and release candidates. If it is a development build it should only check for newer development builds.

### Use case

N/A

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
I think it's good enough for now... :-)
