### ISSUE TITLE
Create a maplist.txt file that is up to date with all the current maps and modes included

### ISSUE THREAD

**Issue by VERsingthegamez** [Joe91/fun-bots#183]
### Requested feature

I'd like to see a maplist.txt file that is up to date with all the current maps and modes included

### Use case

Allows people who make their servers to keep the list up to date

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
@Firjens there was one that was autogenerated before we moved the maplist to the wiki. Maybe we can use a markup-file for the wiki as file in the repo to autogenerate such a list again?
But I don't think that there are that much people using it this way...

**Comment by Firjens** [comment]
> @Firjens there was one that was autogenerated before we moved the maplist to the wiki. Maybe we can use a markup-file for the wiki as file in the repo to autogenerate such a list again?
> But I don't think that there are that much people using it this way...

Yeah this would be too complicated to make without any real benefit.
