### ISSUE TITLE
Bots does not aim the Rhino's HMG when driving.

### ISSUE THREAD

**Issue by KrazyIvan777** [Joe91/fun-bots#186]
### Scope

Vehicle bot behavior

### Enhancement

Bots should be able to aim the Rhino's HMG as the driver operates it, essentially making it handle like an APC.
Currently Bots can only drive and shoot the weapon without aiming.

### Use case

Have bots aim the weapon when firing the HMG when driving the Rhino

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
should be fixed on the Dev-Branch
