### ISSUE TITLE
Support Choppers and Traces for them

### ISSUE THREAD

**Issue by Joe91** [Joe91/fun-bots#188]
### Requested feature

Support Choppers and Traces for them

### Use case

Support Choppers and Traces for them

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Gemini899** [comment]
can't wait for this!
