### ISSUE TITLE
BOTs kills don't register on kill counts/feed

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#19]
Already spoke to Joe about this but I'm registering it on here so others know that it is already being looked at.

When BOTs kill players their kill count does not go up on the scoreboard and there is no entry for the kill in the kill feed.

Joe says that it looks like it may not be possible to do but he's not giving up.

**Comment by Bizarrus** [comment]
We have a brilliant idea for that.

Mostly, the Killvalues cant be modified, thats not a secret. The Scoreboard cant be modified too, another way is to reimplement the scoreboard, but these a bad solution.

Actuall, we have a nice idea for that, but its a secret.

**Comment by Joe91** [comment]
Fragmode was created for that :-)
