### ISSUE TITLE
RUSH NodeCollection bug

### ISSUE THREAD

**Issue by gzbattle** [Joe91/fun-bots#191]
### Bug report token

https://github.com/Joe91/fun-bots/issues/new?assignees=&labels=bug&template=bug-report.yml

### Scope

General bot behavior

### What happened?

New Node Pointlndex does not match

### What was expected?

everything is ok

### How can we reproduce and test it?

add  -updatebranch dev to server and client 
run server 
play sometime and change map 
the server will show you somtingwrong

if you not add this arguments, when you paly rush the server is close , show you wrong.

### Server information (if applicable)

i use 30HZ server with 48 bots paly RUSH.

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by gzbattle** [comment]
![9d4200dc730ee462240185973c3dc7f](https://user-images.githubusercontent.com/89865820/133924994-e970af8b-feb8-49f2-805c-9f4a1fdca3bf.png
![59f55404b48d83d330aa73a64fef1d4](https://user-images.githubusercontent.com/89865820/133924995-02dccd1d-bf57-43f5-9f2d-b4fd7ed90a70.png)
)

**Comment by gzbattle** [comment]
xp5_002 and xp4_parl 
this two map not working with fun bot

**Comment by Firjens** [comment]
Missing bug report token.

**Comment by Joe91** [comment]
Why was it closed? Is the issue fixed?

**Comment by gzbattle** [comment]
C:\Users\GZ\AppData\Local\VeniceUnleashed\client\vu.exe -server -dedicated -updateBranch dev
if you set like this, these two map working
C:\Users\GZ\AppData\Local\VeniceUnleashed\client\vu.exe -server -dedicated 
if you set like this ,these two map can not open with fun bots

**Comment by gzbattle** [comment]
i hope this version can add pass word like before version 

easily to control

**Comment by Joe91** [comment]
If it's working on the dev of VU that means its a bug of VU that they have not released yet.
So all we can do is wait for that fix to go to the prod branch. Sorry.

**Comment by gzbattle** [comment]
thanks your help , it is very nice mod
