### ISSUE TITLE
some bug for bots 

### ISSUE THREAD

**Issue by gzbattle** [Joe91/fun-bots#192]
### Bug report token

https://github.com/Joe91/fun-bots/issues/new?assignees=&labels=bug&template=bug-report.yml

### Scope

General bot behavior

### What happened?

![8d9199fc942f390d799cdba61ae9fdd](https://user-images.githubusercontent.com/89865820/133940943-ab8925c7-4c68-4182-a3e1-f4cf19ee1e72.jpg)
![2fb966d19480caa82d9980034a92646](https://user-images.githubusercontent.com/89865820/133940951-bbd90364-0c9f-4e09-b9bd-b1faba29b9ad.jpg)

i share two picture.

### What was expected?

when i play the game , the round is over, 
but the bots is continue fight behind server, they should be turn off until next round turn on . 

it is  small bug , i think it is easily to fix 

Sometimes it will affect the stability of the server so that the server crashes

and also i have one small desire, it is make Engineering soldier and Support smart， when i finish ammo the bots can give you ammo box, when viechle broken the bots can come repaire/

### How can we reproduce and test it?

you can play TDM SDM TDM-CQ anthore model i can not testing .

make vars.gameModeCounter **100**   this number small , you can testing. At the end of the round 

the bots continue fight .Sometimes it will affect the stability of the server so that the server crashes

### Server information (if applicable)

30hz   48bots

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
should be fixed. will be in next dev-version.

**Comment by gzbattle** [comment]
thinks for your help
