### ISSUE TITLE
RUSH not stable

### ISSUE THREAD

**Issue by gzbattle** [Joe91/fun-bots#193]
### Bug report token

https://github.com/Joe91/fun-bots/issues/new?assignees=&labels=bug&template=bug-report.yml

### Scope

Core

### What happened?

when we play rush with bots , sometime server is crash
![329f152920d4dc70a6a84bf0219586b](https://user-images.githubusercontent.com/89865820/134730078-0d8cca3e-188c-4fcd-9a0c-b8e66d9cf742.png)
![4b2f4d2c95ac92ec4f7c490583feb32](https://user-images.githubusercontent.com/89865820/134730090-beb9b67f-784c-4d7b-82df-62eb6cb45a5b.png)
.

### What was expected?

i am not sure , it is VU some bug or funbots 

### How can we reproduce and test it?

just play rush. and check server

### Server information (if applicable)

60hz 
16 bots one team.

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment]
Missing bug report token.

**Comment by gzbattle** [comment]
it is can be fix , for next dev
