### ISSUE TITLE
The UI interface cannot be replaced with another language

### ISSUE THREAD

**Issue by ccc1206** [Joe91/fun-bots#196]
### Scope

WebUI

### Enhancement

The old version can change the language, and hopefully the new version will follow

### Use case

 can't change the language, it's easy to get a bot set up incorrectly

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
The most of it still works. Will add it again soon.

**Comment by Joe91** [comment]
Added the support for language again. New languages can now be added by using the DEFAULT.js and DEFAULT.lua as template.
