### ISSUE TITLE
Collaboration with the sp-terrains mod by @SassythSasqutch 

### ISSUE THREAD

**Issue by ludslr** [Joe91/fun-bots#199]
### Scope

Core

### Enhancement

traces for at least infantry bots on the new spterrains maps. 

### Use case

allows the fun-bot and spterrains users to enjoy the best of both worlds. :)

### I have checked the following...

- [x] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by ludslr** [comment]
@Joe91

**Comment by Joe91** [comment]
Can you link the mod or the repository you refere to? Then I can have a look at the support in general....

**Comment by Joe91** [comment]
TDM for new maps added. Works so far
