### ISSUE TITLE
Understanding Trace

### ISSUE THREAD

**Issue by Bizarrus** [Joe91/fun-bots#2]
When you start a Trace, will these delete the previous Trace before?

What is the index param on Trace-Command?

If you save the Trace, will be override the previous data?

**Comment by Joe91** [comment]
There are up to 10 Traces per Map. Each of them has an index. If you record Trace 2, and there already was a Trace 2, its deleted. But only for the moment. As long as you don't save it. You also can remove all traces.
If you save the traces, all loaded traces are saved. If you already had 4 Traces and recorded on Trace 2, all others will be saved again, as they were not modified.

**Comment by Bizarrus** [comment]
Okay, thanks for the fast answer!

If you like, you can provide the Source of the UI on the repo. I can make some updates, if you like. On Discord, you had no answer for that.

**Comment by Joe91** [comment]
Yes I would really like that! Someone else is working on it right now, but I will tell him, to put his files there. Shall I add you as member of the repo? Than you can work on your own brach...
I made a Text file with my Ideas on the UI, but we can discuss about all of then ;-)

**Comment by Bizarrus** [comment]
Sounds like good!

If you like, create an special UI-category on discord for ideas/discussions.

**Comment by Joe91** [comment]
As we speak the same language: What is you discord-contact?
