### ISSUE TITLE
All BOTs will sometimes aggro to one player and stay that way no matter their distance or viewing angle

### ISSUE THREAD

**Issue by MajorVictory** [Joe91/fun-bots#20]
I have setup a bot slaughter server with 16 bots on the enemy team. sometimes i will aggro one bot and then suddenly every bot in the server is now facing me and spraying wildly. I have attempted to kick and respawn, kill and respawn, but they continue. It seems once they enter this state, they no longer aggro on any other players.

**Comment by MajorVictory** [comment]
Further testing has revealed that it seems to be triggered by an ammocrate or medicbag. I have my own mod increasing their radius to fill the map, so it seems the bots are detecting this crate and then aggroing to it's owner.

**Comment by MajorVictory** [comment]
I have a solution for you: https://github.com/Joe91/fun-bots/blob/master/ext/Server/BotManager.lua#L174

Change line 174 from:
`if giverInfo.giver ~= nil and soldier.player ~= nil then`
to
`if giverInfo.giver ~= nil and soldier.player ~= nil and info.damage > 0 then`

Then bots will no longer aggro to the owner of a medicbag while in range.

**Comment by Joe91** [comment]
Oh thank you very much!! You are awesome :-)
