### ISSUE TITLE
Bots can use the gunner seat Mobile Artillery

### ISSUE THREAD

**Issue by KrazyIvan777** [Joe91/fun-bots#200]
### Scope

Vehicle bot behavior

### Enhancement

To have bots be able to use the gunner seat on Mobile Artillery vehicles present in the Armored Kill DLC maps. Currently, they can only drive the vehicles but cant use the Missile Launcher since a single operator makes use of separate driver and gunner seats.

### Use case

To have bots drive the Mobile Artillery vehicles and switch seat to the Gunner position once they are in range of an enemy target.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
This issue is still relevant.

**Comment by Joe91** [comment]
Could be possible now. Have to check that.

**Comment by Joe91** [comment]
completed.
