### ISSUE TITLE
Some bugs that I found 

### ISSUE THREAD

**Issue by FlashHit** [Joe91/fun-bots#207]
- [x] `localPlayer` has to be `s_LocalPlayer` https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Client/__init__.lua#L94
- [x] `self.debugSelectionRaytraces` is unknown (got bugged in this commit 8379b545b08fac05cf8ea8cfcd2b2f113b448e32) this has to be `Config.DebugSelectionRaytraces` it seems https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Client/ClientNodeEditor.lua#L2134
- [x] should be `0.05` instead of `0,05` and `0.10` instead of `0,10` https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L78 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L89 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L100 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L111 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L122 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L133 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L144 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L155 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L166 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L177 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L188 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L199 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Settings/SettingsDefinition.lua#L210 
- [x] these two NetEvents call functions that don't exist (got bugged in this commit eb57bb8e309c7b7f6158855274445b0135031eaf) There are 2 functions called `MergeSelection` and `SplitSelection` that should get called. So rename the functions or the NetEvents callbacks. https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/NodeCollection.lua#L44-L45
- [x] `s_ErrorMessage` is not needed here i think. Also remove it a few lines above when you remove it. https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/NodeCollection.lua#L449
- [x] has to be `NetEvents:SendToLocal` or `NetEvents:BroadcastLocal` I guess https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Server/Commands/Chat.lua#L379
- [x] `Bot:_UpdateAiming()` doesn't take any arguments https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Server/Bot.lua#L193
- [x] `self._BotInfo` is unknown https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Server/BotManager.lua#L435
- [x] redundant to return at the end of a function https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Server/BotSpawner.lua#L1357 and https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Server/BotSpawner.lua#L1376
- [x] `string.starts` is unknown I think. It's used here: https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Utilities.lua#L104 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Utilities.lua#L120 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/Utilities.lua#L130 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/WeaponClass.lua#L151 https://github.com/Joe91/fun-bots/blob/d184197e3f0f4697957807a2e40db58aba96a58f/ext/Shared/WeaponClass.lua#L165

**Comment by Joe91** [comment]
Wow, thanks a lot!!
