### ISSUE TITLE
SQDM Spawn bots on all teams but one

### ISSUE THREAD

**Issue by CCInc** [Joe91/fun-bots#209]
### Scope

General bot behavior

### Enhancement

Add an edge case to spawn bots in multiple squads on SQDM even when "spawn bots on all teams" is set to No.

### Use case

My friends and I like to play all of us vs all the bots, so we set TeamSwitchMode=NoTeamSwitch and "Spawn bots on all teams" to No. In general, this does what we want, however on squad deathmatch in particular it will only spawn the bots in one squad (where instead we want all players to be on one squad and the bots to be distributed into the other squads), so bots have to be manually spawned and moved to the other teams.

Is there a better way I should configure this?

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
You are right, this is not handled by the general algorithms. 
So the target case would be to spawn the bots distributed to the two enemy-squads in case of SQDM?
Or would you expect them to also spwan in your "friend"-squad?

**Comment by Joe91** [comment]
I think I would propose to spawn the bots with the setting "Spawn bots on all teams = NO" the following way:
- if and you are in an even team, they spawn in the uneven teams
- if you are in an uneven team, they spawn in the even teams

This would result in the playerteam always playing against enemy-players that you can kill, what in my opinion is the purpose of this setting...
Do you know what I mean with that? What do you think about that?

**Comment by CCInc** [comment]
Sorry, I'm not quite sure I understand - but I think we both agree that the player team will always be playing against all the bot teams.

SQDM has four total teams, so the bots will be spawned in every team except for the chosen "player team" when `Spawn bots on all teams = NO`. And when `Spawn bots on all teams = YES`, the bots will be spawned in every team, including the "player team".

**Comment by Joe91** [comment]
Yeah, but since there are always only RU and US soldiers this will result in having one "friendly" team with you.
If you are in Alpha, Team Charlie will always have "friendly" soldiers that cannot be killed by you (exept you enable friendly fire).
Thats why I think it would be best to distribute them only in the teams that can be killed by your team...

**Comment by FlashHit** [comment]
what do you mean Alpha is Team1, Charlie is Team3. The look of the soldier doesn't matter.

**Comment by Joe91** [comment]
Aah sorry! That was only a bug in VU once ^^
Now I'm with you...

**Comment by Joe91** [comment]
I will try to add this.

**Comment by Joe91** [comment]
Maybe I will have to add the setting again that disables the Bot-Bot-Attack. Because now they will also shoot each other...

**Comment by CCInc** [comment]
I don't mind the bots also attacking each other. We want to play it like a
real game, where each team can shoot all the other teams.

If the bots didn't attack each other, it would basically be TDM :D

**Comment by CCInc** [comment]
Got a chance to test it out. After fiddling with the settings a bit, it seems to be working well!

With Spawn bots on all teams = NO, the bots spawn in 3 enemy teams. With Spawn bots on all teams = YES, the bots spawn on 3 enemy teams and my team. 

Thanks a lot for the patch and the help - let me know if you need me to test anything else for this 😄 I'll update if I see anything after playing with it some more
