### ISSUE TITLE
Discord invitation in the wiki is invalid

### ISSUE THREAD

**Issue by LStuber** [Joe91/fun-bots#212]
Title :) 

I get "invalition invalid or expired" when clicking on it.

**Comment by Joe91** [comment]
Sorry for that. Try this one.
https://discord.gg/kcZmuQDe6e

If this one works I will fix the other Link

**Comment by Joe91** [comment]
At least it seems to work for me. Thanks for letting me know. See you in the Discord Server

**Comment by Joe91** [comment]
Please reopen this If it still does not work for you...
