### ISSUE TITLE
Random Team Switch Option

### ISSUE THREAD

**Issue by Cooper941** [Joe91/fun-bots#213]
### Scope

Core

### Enhancement

In the current build you can make the game switch teams after every round or switch after two rounds but I feel a random option should be added. So on every round start, you're put on a random team. It's not too big of an issue, more of a QOL enhancement.

### Use case

I play on a local server and it would be nice to just select a random map then have it put me on a random team instead of having to manually switch myself over to the other team when I'm on a team that I don't want to be on. 

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Thanks for this feedback! I will have a look at this. Might be fast to implement, but I have to check that...

**Comment by Cooper941** [comment]
> Thanks for this feedback! I will have a look at this. Might be fast to implement, but I have to check that...

Thank you! Hopefully it won't be too difficult to implement.

**Comment by Joe91** [comment]
I added this function on the dev-branch... Can you check if it works the way you intended?

**Comment by Joe91** [comment]
Seems to work fine for me. If there is still an issue with that, just reopen this issue
