### ISSUE TITLE
Bot is constantly shooting

### ISSUE THREAD

**Issue by pinotxo** [Joe91/fun-bots#217]
### Scope

Vehicle bot behavior

### What happened?

When the enemy in the car noticed you, he will shoot at you until he kills . Through walls, through buildings. Example: I'm flying in a helicopter, the anti-aircraft gun noticed me, I sit down on the ground and run behind the building, the anti-aircraft gun continues to shoot at me, although it does not see me.

### What was expected?

Cease fire

### How can we reproduce and test it?

Try to fly over the anti-aircraft guns that are on spawn, map MP_012, there may be others

### Version of fun-bots and VU?

2.5.0 dev9

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by pinotxo** [comment]
It may also happen that a tank is trying to shoot at you through the walls

**Comment by Joe91** [comment]
I will have a look at this.

**Comment by Joe91** [comment]
I think I found the issue. Pushed it on the latest dev-commit.
