### ISSUE TITLE
Sniper rapid-fire

### ISSUE THREAD

**Issue by pinotxo** [Joe91/fun-bots#218]
### Scope

General bot behavior

### What happened?

Sometimes the bot shoots with a sniper rifle as with a machine gun, rapid-fire shooting.

### What was expected?

some rifles fire with a reload

### How can we reproduce and test it?

find the sniper bot

### Version of fun-bots and VU?

v2.5.0 dev9

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Are you sure that it's not a semiauto sniper like a SKS? Other weapons should not support fast firing at all.

**Comment by pinotxo** [comment]
> Вы уверены, что это не полуавтоматическая снайперка типа СКС? Другое оружие вообще не должно поддерживать быструю стрельбу.

SVD shoots single, and bots sometimes shoot rapid.

**Comment by Joe91** [comment]
You are right, the SVD is that fast shootable, so the bots do it that fast. I don't think this is a bug.
The SVD is semiauto and has a Rate of Fire of 260 rpm...

**Comment by Joe91** [comment]
I will increase the Autosniper-Time a little, but not by much. If this is annoying to you, you can just disable this weapon by removing it from the weaponlist...
