### ISSUE TITLE
Bots not leaving a certain flag

### ISSUE THREAD

**Issue by Cooper941** [Joe91/fun-bots#219]
### Scope

General bot behavior

### What happened?

On Azadi Palace (and some other maps), most of the bots on the RU side would stay at a certain objective and run in circles while the US bots capture all the objectives except the one that the RU bots are running in circles around. 

### What was expected?

Most of the RU bots don't go and push objectives and only a few actually go to push objectives but they die due to the US team functioning correctly.

### How can we reproduce and test it?

I played on Azadi Palace with 48 bots, 30hz, and I had the fix for the invisible weapon bug enabled.

Video of the bug:
https://youtu.be/WSFD0eUqC2g

### Version of fun-bots and VU?

fun-bots Release 2.5.0

VU Build #17487

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Hi, this issue is partly because of bad traces. Can you update this issue with every map and exact gamemode you experience this?
Then I or maybe someone else can fix the traces on those maps.
It helps a lot if you say on what exact flag which team does not move anymore...
