### ISSUE TITLE
快点更新

### ISSUE THREAD

**Issue by JoinTiger** [Joe91/fun-bots#223]
### Requested feature

快点更新，都这久了，干什么吃的

### Use case

更新
更新
更新

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment]
Stop shitposting or get blocked.
