### ISSUE TITLE
Bots can shoot through air vehicles 

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#226]
### Scope

General bot behavior

### What happened?

When I was piloting any chopper and running through a general area where bots are populating, they seem to shoot through the vehicle to hit me. As you may know, I was not facing towards the ground when this was happening; I was idling in the air, facing forward to realign, then a random bot _gets a hack_ to shoot through the chopper, hitting me.

### What was expected?

Bullets should not penetrate choppers and other air vehicles. 

### How can we reproduce and test it?

Use any air vehicles and replicate the scenario I described. 

### Version of fun-bots and VU?

Version 2.5.3, VU on latest verison (I cannot remember the detail).

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
I think this behaviour is just realistic, that they can shoot through a window or so. I did not change anything on the engine there. This is mostly just BF3. And tbh I really like that they can shoot you out of a chopper ;-)...
At least I think that most of the time it's just a sniper from far away. Maybe some meshes of some vehicles have bugs as well, but in that case I really have no idea how to fix something like that...

**Comment by koopa990** [comment]
> I think this behaviour is just realistic, that they can shoot through a window or so. I did not change anything on the engine there. This is mostly just BF3. And tbh I really like that they can shoot you out of a chopper ;-)... At least I think that most of the time it's just a sniper from far away. Maybe some meshes of some vehicles have bugs as well, but in that case I really have no idea how to fix something like that...

This happens way TOO often. This should not happen, making it impossible to get the use out of choppers.
