### ISSUE TITLE
Funbots crashes servers with multiple maps/game modes

### ISSUE THREAD

**Issue by yb431** [Joe91/fun-bots#227]
### Scope

Core

### What happened?

There’s a big problem with this mod. When you have multiple maps it crashes VU when switching to a new map. You might get it to switch once but good luck the next time. I checked all other mods I have and took them off 1 by 1. They weren’t the cause. When I left funbots on by itself the same crashes happened that I’ve seen other people complain about. When I took it off funbots I was able to change maps without crashing at all. Please fix this. Without bots VU is kinda useless.

### What was expected?

Should have loaded into the next map.

### How can we reproduce and test it?

Start a server on your own pc with funbots on it and put the maps in the maplist found in the funbots folder in your maplist file. Then change maps. It only happens when switching maps/gamemodes.

### Version of fun-bots and VU?

funbot: i tried both 2.5.3 & 2.6.0 dev2
vu: 18848

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by spatieman** [comment]
as sayd on discord.
its not funbots, as what i understood ,there was a change in the VU core, and funbots is not yet coded with that routine.
give Mr Joe and his team time to find a workaround.

**Comment by okewen** [comment]
This problem has not been solved for so long. I'm so bored that I can't play the game. I hope it can be solved as soon as possible

**Comment by okewen** [comment]
但是为什么一个月了，这个问题一点动静都没有

**Comment by okewen** [comment]
Brother, if this problem is closed, I will relay until it is fixed to

**Comment by bokchoibuddy** [comment]
Fantastic Mod... but fewer and fewer players...because of server and client crashes...need fix

**Comment by Firjens** [comment]
Please keep comments related to the issue. Thank you.

**Comment by okewen** [comment]
When changing the map, the countdown to the settlement is over, it will crash the VU first, but the server will not. At this time, you do not shut down the server, restart the vu, join the server and enter the deployment interface. When loading the BOT, the server side will crash. Not only many maps, but even if there is only one map in the maps file of the server and the mod, it will crash. You cannot start the next round, you can only restart the server and restart the game

**Comment by Joe91** [comment]
I started to investigate this issue a little and I'm quite sure that this is a VU thing. I'm onto it and will let you know when something happens...

**Comment by Joe91** [comment]
can you try if it still happens in the latest dev-commit?
https://github.com/Joe91/fun-bots/tree/dev

**Comment by okewen** [comment]
> 你能试试它是否仍然发生在最新的开发提交中吗？ https://github.com/Joe91/fun-bots/tree/dev

After the test, the map can be rotated normally, but the BOT won't move

**Comment by Joe91** [comment]
They move for me. Do you use any other mods?What exactly do you do that they don't move anymore?Am 29.08.2022 19:48 schrieb okewen ***@***.***>:



你能试试它是否仍然发生在最新的开发提交中吗？ https://github.com/Joe91/fun-bots/tree/dev



After the test, the map can be rotated normally, but the BOT won't move

**Comment by OsQw3rty** [comment]
> Please make sure to use the dev-Version of VU! Otherwise this versin won't work at all. To use the dev-version you have to add this to the target of VU: -updateBranch dev

Hello,
Been eyeballing this issue as I'm trying run server of my own. I can confirm that this works. The "-updateBranch dev" needs to be added to both client and server side. And when launching client, it takes a while to complete the update once vu starts.

**Comment by Joe91** [comment]
Thanks a lot for that feedback!
This will soon become the new prod-version so it won't be needed for that long anymore.

**Comment by Firjens** [comment]
Issue resolved.
