### ISSUE TITLE
Adding bot pathfinding for XP1_004 RushLarge0

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#233]
### Scope

Other

### Enhancement

I found that Wake Island lacks a path for the rush mode. Can you add a robot path for this mode? thanks

### Use case

The current map code of this mode is as follows:：XP5_004 RushLarge0 1.I hope you can add the path of this mode in your busy schedule. I will be very grateful. Thank you

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
XP5_004 is not wake-island but already supported.
Do you mean XP1_004 or something else?

**Comment by Augustakit** [comment]
yes,it'sXP1-004 map.I'm wrong
