### ISSUE TITLE
Latest VU Cannot load in fun-bots

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#235]
### Scope

Core

### What happened?

I recently downloaded and integrate fun-bots 2.6.1 dev2 on my system. As I boot into my server, nothing show s up.

### What was expected?

to work

### How can we reproduce and test it?

I dont know if it is VU or your end.

### Version of fun-bots and VU?

release 2.6.1 dev2

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment]
Launch the server in dev mode.
