### ISSUE TITLE
The client automatically exits

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#236]
### Scope

Core

### What happened?

When I started playing the second map, the game automatically quit without any error messages

### What was expected?

I wish I could play the map all the time

### How can we reproduce and test it?

I just changed the language options and the number of bots to 64.There are also MapEditsLoader, BetterBF3Visual Mod, VEManager these modules.However, in previous versions these mods were run without problems

### Version of fun-bots and VU?

funbots version:2.61-dev4
vu version:#19412

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment]
Can you provide more information and clear reproduction steps?

**Comment by Augustakit** [comment]
Here is a picture of me starting the game, just after the end of the first round, after the end of the second round, a list of my modules and a list of the maps I used.I still use newer versions, such as dev5, but strangely it still leaves the client without any errors
![1](https://user-images.githubusercontent.com/102933021/193809397-5be81ce0-dd6e-4974-98d9-565c73a2491c.jpg)
![2](https://user-images.githubusercontent.com/102933021/193809411-fa1fb030-d431-4dea-875a-5c789fb99104.jpg)
![3](https://user-images.githubusercontent.com/102933021/193809427-209e6940-a14c-4232-9473-80d4e7793314.jpg)
![4](https://user-images.githubusercontent.com/102933021/193809449-9bd9ff96-d404-44ee-acd0-4df455e7e476.jpg)
![5](https://user-images.githubusercontent.com/102933021/193809464-65d65a11-1a20-4b3d-9917-c81c65306d80.jpg)

**Comment by Augustakit** [comment]
At first I thought it was the name of the mod. Later I tried to change the name of the mod to what it was when it was downloaded, but it didn't work and I was using the latest version of VU

**Comment by FlashHit** [comment]
Does it crash if you run only the fun-bots mod? So, no other mods, just fun-bots.

**Comment by Augustakit** [comment]
Just running the Funbots module won't crash, but this one hasn't had this type of problem before

**Comment by Firjens** [comment]
Unable to replicate.

Note: when creating an issue do not lie about your environment. (Eg. Checking the box that you only run fun-bots whilst you also run other mods).
