### ISSUE TITLE
Discord link invalid, not sure if I'm meant to use the source code

### ISSUE THREAD

**Issue by dfgdgdgfd** [Joe91/fun-bots#242]
I click releases but the only options to download are two zips of source code.  Went to use the discord link but it's an invalid url - found another discord link but the invite is invalid.

**Comment by Joe91** [comment]
Just download the source-code. The source-code is the mod.
Sorry for the invalid link. Have to check why it is not working...
Can you try this new link:
https://discord.gg/FKamccAEqz

**Comment by Firjens** [comment]
That invite link works.
