### ISSUE TITLE
dark mode for `fun-bots-helper.py`

### ISSUE THREAD

**Issue by joao-vitor-souza** [Joe91/fun-bots#244]
### Requested feature

It would be interesting if `dev/fun-bots-helper/fun-bots-helper.py` had a darkmode just like [this](https://github.com/rdbende/Azure-ttk-theme). Seems not that hard to implement it.

### Use case

It improves the visuals of the application.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Great suggestion! I don't think we need the light-theme at all :-). I just did the most simple UI possible for it and left it this way. Happy on any improvement.
Would you like to do that or shall I have a look at?

**Comment by Joe91** [comment]
Merged PR
