### ISSUE TITLE
Dont even know where to start...

### ISSUE THREAD

**Issue by mostfurious** [Joe91/fun-bots#25]
Hello.

Started to experience a lot of problems with your bots.
First of all it started spueing erros in the console:
```
Error: stack index 3, expected number, received nil: stack traceback:[C]: in method 'CreatePlayer'[string "BotManager.lua"]:272: in method 'createBot'[string "BotSpawner.lua"]:104: in method 'onLevelLoaded'[string "__init__.lua"]:90
```

And then bots sometimes dont spawn at all.
Changing settings in `Config.lua` doesnt work... fully.
When it started showing erros i re-downloaded this mod and uploaded it to server folder expecting to see that erros would be gone but no.. they are still here.

Another thing that i noticed is that once i moved `Config.lua` from old folder to a newly re-downloaded folder, the bot difficulty changed to what i set it to.

If i try to save changes while in-game with `F12` some changes persist, some dont...
 * Am i doing something wrong?
 * Are there any temp files that i can remove for the changes to take effect on server reboot ?
 * And what about those erros?

**Comment by Bizarrus** [comment]
Had edited your issue for clean reading.

**Comment by Joe91** [comment]
What version of the mod are you using? Did you replace all files from the mod-folder? What gamemode are you playing on?

**Comment by mostfurious** [comment]
Dont know what version im using, i downloaded it directly from here yesterday. Removed the whole folder and unzip the new one instead. In the newly downloaded folder i only replaced the config file from the old one.
Game mode is TDM

**Comment by Joe91** [comment]
Version is inside the main folder (mod.json). (V1.5.0.3 is the latest release)
I ran servers for several hours without any errors in the log at all. The Line the error refers to is when a new Player is created. Do you use some other mods retlated to Player-Creation or Squad modification? Aslo: Have you tried it without modifiying the Config at the beginning? 
I really want to help you, but as I can't reproduce the error (thats what I want to start with) I need a little more help...

**Comment by mostfurious** [comment]
The only other mod that i use is vu-mapvote
