### ISSUE TITLE
Aygan Village map bot crash issue.

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#273]
### Scope

General bot behavior

### What happened?

When I play "COOP_006 TeamDeathMatch0 1" this mode, once the number of robots exceeds 20, the game has the probability of crashing.

### What was expected?

I hope this chart can accommodate up to 32 bots per team.

### How can we reproduce and test it?

It is not clear why it crashes, I just play according to the default configuration.

### Version of fun-bots and VU?

fun-bots-2.62 .vu#19412 version.The vu-all-gamemodes-in-all-maps and CustomLevelLoader mods are used, which are necessary to load this map, and the other modules are not used.And the author of the two mods, keku645, told me that his map was working fine and there was nothing wrong with it.

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment]
Do not provide false information on issues. (Eg. selecting that you run no other mods while you do). Try to reproduce it without other mods.

**Comment by Augustakit** [comment]
I may have misrepresented it, but without those two modules, COOP_006 TeamDeathMatch0 1 is not working.
