### ISSUE TITLE
Bots get stuck stuck as pilot for choppers (chopper won't take off)

### ISSUE THREAD

**Issue by Digitalinsite** [Joe91/fun-bots#275]
### Scope

Vehicle bot behavior

### What happened?

Not sure if this has already been posted or not but I've noticed that several times bots get stuck when they try to pilot a chopper (Attack chopper and venom). Happens on both RU and US teams. What I've noticed is that the bot gets in the pilot seat and doesn't take off but the engine is running. If I use the command menu and ask them to exit the vehicle they do but then they run circles around the chopper. If I try to fly the chopper, I can only get about 1 foot off the ground and it won't fly as if it's stuck by a magnet. I find that If i get out and RPG or C4 that chopper and it respawns another then it usually fixes it for a while. I've seen it happen on my own team being US as well as RU and I've also been to the opposing team base and seen them stuck there too. If I kill that chopper it usually fixes it. It doesn't happen all the time though and seems to be more on certain maps. I just ran a match and saw it happen for both US and RU on Caspian Border Conquest 20 vs 20. Odd one because it doesn't always happen though. Do you think it might be a bot trace issue? It almost feels like the chopper is being grounded as part of the code waiting for an event,

### What was expected?

Expected to see pilots fly as per normal. 

### How can we reproduce and test it?

Caspian Border Conquest 20 vs 20. Friendly fire on. 

### Version of fun-bots and VU?

V2.6.2

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by toba-zz** [comment]
I think you talk about this
[https://youtu.be/mnyM3FrAufM](url)

**Comment by Digitalinsite** [comment]
yep @toba-zz that's exactly what happens. thanks for the link. Glad it's not just me. Not sure what causes it though, I'm wondering if it's a certain class or a bot with a certain kit trying to fly the choppers and bugging out. It's weird though because even if you teamkill the bot it still magneto locks the chopper to the ground until you RPG it. So it's like some piloting code gets locked to that instance of the chopper (maybe the wait for passenger part of the code??)

Doesn't happen all the time either, sometimes bots will fly the choppers no problems maybe 10 times in a row or so and then it happens - sometimes it's even early on in the round.  Apart from that the bots are awesome and looking forward to any future updates (plane dogfights will be epic if possible :)

**Comment by Joe91** [comment]
Hi, I already tried to investigate this but I really had problems to reproduce this. If you find a way to do this kind of fast it would help me a lot to investigate what exactly happens there. Have seen it myself as well, but I was not able to identify what's wrong at all...

**Comment by Digitalinsite** [comment]
Sure - I'll see if it happens on the new 2.7.0 RC1 and record it. thanks again
