### ISSUE TITLE
Aim penalty variable for bots tracking you in a vehicle

### ISSUE THREAD

**Issue by Digitalinsite** [Joe91/fun-bots#276]
### Scope

General bot behavior

### Enhancement

Variable to change bots aiming multiplier if aiming at someone in a vehicle

### Use case

I've noticed that bots have exactly the same aim whether you're on the ground or whether you are in a vehicle moving fast - eg. in a fast-moving Jeep or a chopper and they seem to be able to aimbot kill you with perfect accuracy out of the sky or across landscape even though you're moving really fast. I'm wondering if a variable can be added to the settings that worsens their aim if they are aiming at a vehicle like in the same way you have the different aim stats for snipers and normal Infantry etc. I think it would really improve the gameplay if they can't shoot Choppers out of the sky, jeeps and planes using small arms and rifles so easily. I was thinking of giving them maybe 50% I'm penalty or something like that if they are tracking you in a vehicle.

Thanks again for all your hard work on this mod. Total game changer

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Like the idea. I could just increase the error related to the speed with the skill-factor. Will play around a little with that when I start to add this.

**Comment by Digitalinsite** [comment]
Awesome - thanks. I just gave the new 2.7.0 RC1 a shot, awesome stuff and really loving the new changes and fixes! thanks again bro

**Comment by Joe91** [comment]
I modified the aim-error on larger distances (v2.8.0-dev8). Not sure if I'm happey with this already, but it's getting in the right direction.
You can further modify this by changing the "WORSENING_FACOTR_DISTANCE" in the Registry.lua. Sorry for the long delay on this.
Happe to hear from you and if this goes in the right direction...
