### ISSUE TITLE
teams always outnumber by 4 bots

### ISSUE THREAD

**Issue by xakidash** [Joe91/fun-bots#278]
### Scope

Core

### What happened?

me and my friend are trying to play and nice even match however 4 or 2 bots always spawn on the enemy team making it uneven and outnumbering

ive currently only tried this on Caspian border on conquest large

### What was expected?

it should be 50 50 on both teams

### How can we reproduce and test it?

![image](https://user-images.githubusercontent.com/121055246/210188881-248803ad-aab1-4a0a-aaab-b5cf45f52f78.png)

### Version of fun-bots and VU?

fun bots 2.70

VU Cilent 19968

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment]
Hello.

This can be done using the configuration file. If you need help use the #support section on Discord.

Regards.
