### ISSUE TITLE
Caspian Border PathSwitcher.lua errors

### ISSUE THREAD

**Issue by koboltzz** [Joe91/fun-bots#281]
### Scope

Core

### What happened?

Hello,
I am playing "MP_007 ConquestSmall0 1" with "fun-bots-2.7.0-RC1" on Windows 11 x64. The bots work somehow, but right after the first player joins the server, it jerks around. This has nothing to do with the FPS, which are more than enough. Rather the bots twitch back and forth as they move around. Almost as if their ping was gigantically high. A look into the server console tells us that the error 
`[error][VeniceEXT][fun-bots-2.7.0-RC1]Error: [string "PathSwitcher.lua"]:120 attempt to index a nil value ['field Objectives']stack traceback:[string "PathSwitcher.lua"]:120 in method 'GetNewPath'[string "Bot/BotMovement.lua"]:333 in method 'UpdateNormalMovement'[string "Bot.lua"]:253 in method 'OnUpdatePassPostFrame'[string "BotManager.lua"]:72 in method 'OnUpdateManagerUpdate'[string "__init__.lua"]:248 in function <[string "__init__.lua"]:247`
is logged several times per second without interruption. This leads to massive server performance drop.

### What was expected?

Bots move normally and server log is not flooded with errors.

### How can we reproduce and test it?

No special setup, just "MP_007 ConquestSmall0 1" and "fun-bots-2.7.0-RC1". Sure I have other mods, but this error also happens even I delete all mods except fun bots.

### Version of fun-bots and VU?

fun-bots-2.7.0-RC1, latest VU.zip from their homepage

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
should be fixed on 2.7.1
