### ISSUE TITLE
Bots don't damage each other nor the player.

### ISSUE THREAD

**Issue by HoracioKingston** [Joe91/fun-bots#282]
### Scope

General bot behavior

### What happened?

Hello, thank you so much for making this mod!

Unfortunately though, when I tried it, the bots don't seem to damage anyone. Yes, I've tweaked their accuracy to be pinpoint, and they fire at each other and suppress the player, but no damage to them whatsoever.

They work fine when doing objectives, but anything they wield, be it weapons, pistols, snipers, or knives and they just suppress the player. What I do see is how bots would flinch when being hit, the player also has visible damage indicators when hit, but no effect to their health.

### What was expected?

They should have killed each other, but they're only left shooting each other with no damages. The only things that could actually kill the player are bot thrown grenades, operated vehicles, and a few shotguns like the Saiga. Anything else and they just shoot at each other with no damage to either of them.

### How can we reproduce and test it?

No other mods are being used, no custom tweaks to the player's health, no custom tweaks to the bots' health, even with the damage multiplier, nothing happens. Resetting to their default settings do nothing as well. Reducing the bot count doesn't work, either. Switching to maps and different game modes still give the same result...

### Version of fun-bots and VU?

Both the latest release and the one previous, version 2.4.0, which I tried downgrading to, only being met with the same result.

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Are you sure you are using V2.7.1?
Can you try to run this mod without modifications?

**Comment by HoracioKingston** [comment]
Mhm, I'm testing it right now, but still no damages. I took videos.

**Comment by HoracioKingston** [comment]
https://user-images.githubusercontent.com/124144617/216025436-a85db72a-7104-4db6-9489-310319c89a07.mp4

Here's one. Apologies for the low quality due to compression.

**Comment by HoracioKingston** [comment]
Here's another. As you can see, I died by a grenade, but that was pretty much it. Another kill popped up on the killfeed, but there were no other weapon kills. 
https://user-images.githubusercontent.com/124144617/216025773-656cf321-486d-46ba-8c03-ca7490a34469.mp4

**Comment by Joe91** [comment]
Is there any way how to reproduce this issue? Does this happen every time or only from time to time? Will it disapear or stay like this forever?

**Comment by HoracioKingston** [comment]
After extensive playing, bots ONLY seem to damage and kill with shotguns loaded with HE rounds. That's pretty much how I've been playing since then. 

To reproduce the issue, I reset the settings to default, no mods, latest version of both the mod and Venice Unleashed. The bot's loadouts use the class loadouts, no damage multiplier. 

How I worked around the issue is to arm all bots with shotguns loaded with HE rounds. Grenades and Anti Tank weapons work. BTR and Tank rounds kill but coaxials merely suppress.

**Comment by Joe91** [comment]
This is really strange and does not happen on my system at all. Can you tell me the exact version you are using?
And can you also try the dev-branch?

**Comment by HoracioKingston** [comment]
Hello! Thank you so much!!
Sorry for the late response but the issue has now been resolved with the branch you gave me!! All settings reset to default and all bots now kill each other with every weapon.

Thank you for your hard work and dedication to this mod, from the bottom of my heart!

**Comment by Firjens** [comment]
> Hello! Thank you so much!! Sorry for the late response but the issue has now been resolved with the branch you gave me!! All settings reset to default and all bots now kill each other with every weapon.
> 
> Thank you for your hard work and dedication to this mod, from the bottom of my heart!

Issue resolved.
