### ISSUE TITLE
Wrong Death Kill Alert

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#283]
### Scope

Other

### What happened?

I'm playing the game and I have a problem that when I use funbots-2.80-dev1, sometimes the bots don't show bot damage after killing me, instead they show a suicide like message. How can I fix this?
I haven't loaded any other modules, and I've tested both versions 19968 and 19969 for example, and found this to be the case.

### What was expected?

I hope that after death, it will show bot killing rather than suicide

### How can we reproduce and test it?

My startup file
vars.roundStartPlayerCount 1
vars.maxPlayers 64
vars.gameModeCounter 100
vars.playerManDownTime 10
vars.playerRespawnTime 10
vars.autoBalance true
vu.ColorCorrectionEnabled false
vu.SunFlareEnabled false
vu.DisablePreRound true

### Version of fun-bots and VU?

VU:19968 and19969 version
funbots:fun-bots-2.8.0-dev1

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Augustakit** [comment]
Uploading video_20230203_134111.mp4…

**Comment by Joe91** [comment]
For the moment just disable the meele-attack of the bots. Trying to find a better solution, but that's all that is possible for the moment...

**Comment by Joe91** [comment]
should not happen on v2.8.0-dev2 anymore...
https://github.com/Joe91/fun-bots/releases/tag/v2.8.0-dev2
If you want them to use the knive again just change the registry-value "USE_BUGGED_HITBOXES" to true...
