### ISSUE TITLE
Crashed And I collect some log

### ISSUE THREAD

**Issue by lijingjian001** [Joe91/fun-bots#284]
### Scope

Other

### What happened?

[2023-02-04 13:52:05+08:00] [error] [VeniceEXT] [fun-bots-2.7.1] Error: [string "GameDirector.lua"]:473: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
	[C]: in metamethod 'index'
	[string "GameDirector.lua"]:473: in method 'OnVehicleEnter'
	[string "__init__.lua"]:459: in function <[string "__init__.lua"]:458>
	[C]: in method 'EnterVehicle'
	[string "Bot.lua"]:1295: in method '_EnterVehicleEntity'
	[string "BotSpawner.lua"]:1082: in method '_SpawnSingleWayBot'
	[string "BotSpawner.lua"]:289: in method 'OnRespawnBot'
	[string "__init__.lua"]:526: in function <[string "__init__.lua"]:525>
	[C]: in method 'DispatchLocal'
	[string "Bot.lua"]:1182: in method '_UpdateRespawn'
	[string "Bot.lua"]:206: in method 'OnUpdatePassPostFrame'
	[string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
	[string "__init__.lua"]:248: in function <[string "__init__.lua"]:247>
[2023-02-04 13:52:17+08:00] [error] [VeniceEXT] [fun-bots-2.7.1] Error: [string "GameDirector.lua"]:473: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
	[C]: in metamethod 'index'
	[string "GameDirector.lua"]:473: in method 'OnVehicleEnter'
	[string "__init__.lua"]:459: in function <[string "__init__.lua"]:458>
	[C]: in method 'EnterVehicle'
	[string "Bot.lua"]:1295: in method '_EnterVehicleEntity'
	[string "BotSpawner.lua"]:1151: in method '_SpawnSingleWayBot'
	[string "BotSpawner.lua"]:289: in method 'OnRespawnBot'
	[string "__init__.lua"]:526: in function <[string "__init__.lua"]:525>
	[C]: in method 'DispatchLocal'
	[string "Bot.lua"]:1182: in method '_UpdateRespawn'
	[string "Bot.lua"]:206: in method 'OnUpdatePassPostFrame'
	[string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
	[string "__init__.lua"]:248: in function <[string "__init__.lua"]:247>
[2023-02-04 13:52:34+08:00] [error] [VeniceEXT] [fun-bots-2.7.1] Error: [string "GameDirector.lua"]:473: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
	[C]: in metamethod 'index'
	[string "GameDirector.lua"]:473: in method 'OnVehicleEnter'
	[string "__init__.lua"]:459: in function <[string "__init__.lua"]:458>
	[C]: in method 'EnterVehicle'
	[string "Bot.lua"]:1295: in function <[string "Bot.lua"]:1254>
	(...tail calls...)
	[string "Bot/BotMovement.lua"]:68: in method 'UpdateNormalMovement'
	[string "Bot.lua"]:252: in method 'OnUpdatePassPostFrame'
	[string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
	[string "__init__.lua"]:248: in function <[string "__init__.lua"]:247>
[2023-02-04 13:53:03+08:00] [error] [VeniceEXT] [fun-bots-2.7.1] Error: [string "GameDirector.lua"]:473: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
	[C]: in metamethod 'index'
	[string "GameDirector.lua"]:473: in method 'OnVehicleEnter'
	[string "__init__.lua"]:459: in function <[string "__init__.lua"]:458>
	[C]: in method 'EnterVehicle'
	[string "Bot.lua"]:1295: in function <[string "Bot.lua"]:1254>
	(...tail calls...)
	[string "Bot/BotMovement.lua"]:68: in method 'UpdateNormalMovement'
	[string "Bot.lua"]:252: in method 'OnUpdatePassPostFrame'
	[string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
	[string "__init__.lua"]:248: in function <[string "__init__.lua"]:247>
[2023-02-04 13:53:04+08:00] [info] [VeniceEXT] [artifacts] Skip picking random maps: maplist is too short (161) compared to mapvote.limit (161), mapvote.excludeCurrentMap: false
[2023-02-04 13:53:04+08:00] [info] [VeniceEXT] [artifacts] mapvote.randomize true, shuffling maps
[2023-02-04 13:53:04+08:00] [info] [VeniceEXT] [artifacts] Starting mapvote
[2023-02-04 13:53:04+08:00] [error] [VeniceEXT] [fun-bots-2.7.1] Error: [string "Bot.lua"]:199: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
	[C]: in method 'SingleStepEntry'
	[string "Bot.lua"]:199: in method 'OnUpdatePassPostFrame'

### What was expected?

no crash

### How can we reproduce and test it?

almost every round  crash when round have vehicle......

### Version of fun-bots and VU?

fun-bots release 2.7.1。

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Can you try to repoduce this bug without other mods like map-vote?
