### ISSUE TITLE
routine in bot can crash server on end round

### ISSUE THREAD

**Issue by spatieman** [Joe91/fun-bots#288]
### Scope

Core

### What happened?

2023-02-09 16:57:58+01:00] [error] [VeniceEXT] [fun-bots-master280dev2] Error: [string "Bot.lua"]:199: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
        [C]: in method 'SingleStepEntry'
        [string "Bot.lua"]:199: in method 'OnUpdatePassPostFrame'
        [string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
        [string "__init__.lua"]:248: in function <[string "__init__.lua"]:247>
--- RESTARTING SERVER ---

### What was expected?

should not happen ,and normal map end routine should start.

### How can we reproduce and test it?

randomly, cant force it here.

### Version of fun-bots and VU?

fun-bots-master280dev2 - VU 19968 DEV

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
this is really strange. I already check if the soldier is nil before calling this method. I don't think there is anything else I can do there. Maybe this can be fixed on the VU side if we are able to reproduce this issue fast...

**Comment by spatieman** [comment]
Thank Mr Joe.
As i noticed, it happens most of time on grand bazar here (with Bflag mod,and yes, also without it it can happen)
rarely on other the other maps, but most of time ,there where buildings nearby.
what i noticed in the time writing this and topic start, it looks sudenly that on the last second i end up for a split second under the map.
it happens with version DEV 1 and 2, also with 271, i also have the idea that it can be a server isue.
Runing latest DEV as server and also as client..

again,as sayd, it happens randomly, not always, i can play 4 round on a row, than sudenly 2 rounds where the server is crashing.

**Comment by germanc6** [comment]
Hi, i also get a crash when changing the map. im using funbots 2.7.1 and no other mod.
This is part of the dump:
[string "Bot.lua"]:199: tried accessing an invalid or destroyed EntityBusPeer
stack traceback:
    [C]: in method 'SingleStepEntry'
    [string "Bot.lua"]:199: in method 'OnUpdatePassPostFrame'
    [string "BotManager.lua"]:72: in method 'OnUpdateManagerUpdate'
    [string "init.lua"]:248: in function <[string "init.lua"]:247

**Comment by spatieman** [comment]
we simply should wait for a fix and the VU crew gives more code info to Mr Joe..

**Comment by BigShottt** [comment]
I've been experiencing the same end of round crashes without mods, only funbots installed and VU. It happens with v2.7.1 as well as 2.8.0dev2...only way to stop crash at end of round (last ticket remains) is to remove funbots.

Hope it gets fixed soon. I'm a strict PvE'er...I don't play PvP so I really only play BF3 for the bot play and this mod.

**Comment by Joe91** [comment]
I'm working on it but it is really strange and confusing. Had some tries, but they all just don't fix this...
Hope beeing able to provide an update on this soon...

**Comment by germanc6** [comment]
> I'm working on it but it is really strange and confusing. Had some tries, but they all just don't fix this... Hope beeing able to provide an update on this soon...

take your time man and thanks for the mod. will you be doing a mod for Warsaw Revamped too?

**Comment by Joe91** [comment]
@FlashHit found the fix for this bug! It's included in the new dev-version:
https://github.com/Joe91/fun-bots/releases/tag/v2.8.0-dev4
