### ISSUE TITLE
Menu not showing GUI

### ISSUE THREAD

**Issue by Kitsuneet** [Joe91/fun-bots#294]
### Scope

Core

### What happened?

I've recently reinstalled VU, ProCon , and BF3 again, as well as updating everything to ensure a fresh start. No other mods has been installed so far.

After starting my server and granting myself the Admin settings, I tried to open the Bot Menu, but it unfortunately is not appearing.

The mouse icon itself shows and my character stops moving/all actions, but there's not menu to be found.

I've adjusted the resolution, checked the server settings, restarted the server multiple times, disable any overlay that could affect it (AMD Metrics).

The maps and gamemodes are supported and the bots do spawn, but I can't see the FB GUI for some reason.

### What was expected?

The menu should have appeared, but I'm only seeing the cursor.

### How can we reproduce and test it?

Perfrom a fresh install of BF3, VU, ProCon, and the bot mods.

### Version of fun-bots and VU?

FunBots 2.7.1 Latest
VU Latest Version (19989).

Running no other mods.

Ryzen 5 5600X
RX 6700XT
32GB 3200MHz
Samsung Evo 980

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Really sorry to hear that. But as far as I can tell there is no issue at all for me (and many others using VU).
But maybe you can try to reinstall VU once again? Maybe reinstall it with admin-rights?
