### ISSUE TITLE
Bots walk on vehicle paths

### ISSUE THREAD

**Issue by tagener-noisu** [Joe91/fun-bots#297]
### Scope

General bot behavior

### What happened?

Sometimes when bots exit vehicles or just spawn on players, they go for the closest path, which could be a land vehicle path.

The problem with vehicle paths is that sometimes trace creators don't connect them with infantry paths and bots can't reach their objectives, sometimes they just walk back and forth if the path is not looped. Also vehicle paths have speed modes that don't really work for infantry, so you can see bots going prone in the middle of a road.

### What was expected?

Let bots walk on vehicle paths. They should ignore speed modes if they are on a vehicle path.

And then we have these options:
- Make bots switch paths as soon as they find a connected infantry path and never go back on vehicle paths. It requires checking and fixing all vehicle traces that are not connected to any infantry traces on each map.
- Make bots search for closest infantry paths inside a given radius. Switch as soon as a viable path is found. Not sure about the performance of this solution yet.

I could fix that myself, but I want to hear your opinions and ideas.

### How can we reproduce and test it?

Create two paths, one vehicle path and one infantry path. Connect them and spawn a bot.

### Version of fun-bots and VU?

fun-bots 2.8.0-dev5

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Would you mind to create a short trace that reproduces this issue fast? That would help me a lot on this topic...

**Comment by tagener-noisu** [comment]
[XP5_003_ConquestLarge0.zip](https://github.com/Joe91/fun-bots/files/12164923/XP5_003_ConquestLarge0.zip)
It for Kiasar Railroad. Don't use any vehicles. Go to objective A and capture it, while standing on the vehicle path. You'll see that after capturing it your squad will spawn on you and start to walk on the vehicle path.
I tried to fix that by connecting the infantry path, and they use it sometimes, but sometimes they walk back on the vehicle path.

**Comment by Joe91** [comment]
Thank you very much! This helps a lot! Seems that I missed some logic on the "spawn at player" things. Should be able to fix this soon with this map!

**Comment by tagener-noisu** [comment]
Well it's not just the spawn at player. The same thing would be with bots leaving a disabled vehicle. I think we should allow them to walk on vehicle paths, until they find the closest infantry path and switch to it.

**Comment by Joe91** [comment]
Well in that case we would have the same issue again, that if there is no connection to an infertery-path they will stay on that path forever. I think I found the issue. For now I would suggest to force infantery to always use infertery-paths in these events...

**Comment by Joe91** [comment]
I pushed it into the dev-branch. If you want you can try it out and check if it works this way for you...

**Comment by Joe91** [comment]
Will close it for now. If it happens again, just reopen this issue and we can continue on it...
