### ISSUE TITLE
Rubberbanding (2.8.0-dev5)

### ISSUE THREAD

**Issue by Legacy7K** [Joe91/fun-bots#299]
### Scope

Core

### What happened?

I now rubberband on dev5 2.8.0 with only 32 bots. I used to play 64 bots without lag but now it rubberbands with even 32 bots. It usually happens when I get close to the enemy team or the center of the map. I just want to play VU with fun-bots but these problems happen out of nowhere. Its not a spec issue. I get very steady FPS even on 64 bots (32 each team) i7-700K, GTX 1080ti,16GB Ram and 4.5TB SSD
![image](https://github.com/Joe91/fun-bots/assets/140185842/649a217a-121f-4e20-acc7-ce7ec916cbe6)

### What was expected?

Not rubberbanding.

### How can we reproduce and test it?

Im not sure what causes the problem so I don't know how to recreate it.

### Version of fun-bots and VU?

fun-bots Dev5 2.8.0. The latest version of VU as of 21/07/2023

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by tagener-noisu** [comment]
Strange. Looks like there's something wrong with your mod.db file. Is it updated to the last version too?
Try this: open fun-bots settings with F12, go to Advanced tab and set "Speed  factor vehicle attack" to 0.6

**Comment by Legacy7K** [comment]
Its blank. Why is it blank and why cant i change it?

**Comment by Legacy7K** [comment]
![image](https://github.com/Joe91/fun-bots/assets/140185842/a3812b25-6399-475d-b315-38254cf63a00)
![image](https://github.com/Joe91/fun-bots/assets/140185842/4d94ee71-1af9-4062-ad45-befcf7acf28c)
Look. F12 doesnt let me change the option and its blank. In the Config.lua there is no line that says "Speed factor vehicle attack". Do you know the exact name for the line and ill put it in the Config.lua?

**Comment by Legacy7K** [comment]
I fixed the problem. For some reason the command for Speed factor vehicle attack wasnt in my Config.lua and i recopied it from one if the old funbots i has installed

**Comment by Legacy7K** [comment]
Thanks to you tagener i wouldnt of known to check that. Love you bor

**Comment by Joe91** [comment]
You should never just copy the config.lua.
You can export your settings (and restore them) with the fun-bots-helper...

**Comment by Legacy7K** [comment]
I didn't copy the Config i copied the missing code

**Comment by Joe91** [comment]
But the code is there. I don't unterstand how else it could disapear for you:
https://github.com/Joe91/fun-bots/blob/dev/ext/Shared/Config.lua#L134

**Comment by Legacy7K** [comment]
Well it wasnt there

**Comment by Joe91** [comment]
Really strange than. We can just keep this closed for now and if it happens again we can maybe find out little faster how it could happen.
Thanks a lot for your help on this!
