### ISSUE TITLE
Vehicle aim adjustments

### ISSUE THREAD

**Issue by Legacy7K** [Joe91/fun-bots#302]
### Requested feature

Make Tanks, AT or AA vehicle Turret aim and LMG less aim bot like?

### Use case

It improves the realism of the vehicles as tanks and other vehicle guns irl are a lot more difficult to aim.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
added in 2.8-dev8. Can be modified in the Settings.
