### ISSUE TITLE
Path editor Loop and Reverse 

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#304]
### Scope

Telemetry

### What happened?

Whenever I change the default Loop path to Reverse, and hit Save, they revert back to Loop on map restart and reboot. This can be a problem for bots that are taking that path towards the next Stage because some often go out of the MCOM loop area, and go reverse to the finished Zone.

### What was expected?

Never have them abandon the MCOM loop area.

### How can we reproduce and test it?

With enough time of waiting, you can spot out a single bot or two going in the wrong direction, towards attacker base.

### Version of fun-bots and VU?

2.8.0 dev6

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Thanks a lot for finding this issue! Must have been there quite a while now...
Was able to fix it on the dev-branch.
