### ISSUE TITLE
Gun Master Bots infinite M-SAW

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#305]
### Scope

General bot behavior

### What happened?

In the Gun master preset "US Arms race", at the second to last tier, game has the US version of the RPG. To put it bluntly, they fire infinitely instead of reloading.

### What was expected?

never have infinite clip

### How can we reproduce and test it?

US arms race 

### Version of fun-bots and VU?

2.8.0 RC1

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Think I might have fixed it with this commit on the dev brach. If it still happens, just let me know...
