### ISSUE TITLE
Auto kill bots that have unknown current objective

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#307]
### Requested feature

When bots accidentally spawn on a path that leads to nowhere, cant progress up to next stage in Rush, or anything that they are not participating in battle, let the mod auto kill those bots.

### Use case

To avoid the lack of bot counts that are progressing towards their designated objective paths.

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Hi, I tried to add this feature on the dev-branch. Can you maybe try it out this way? There is a timer now that counts up to a Registry-Value (default 35 s atm). If a Bot attacks someone it resets and if the bot is on a valid path it also resets.
Still no tweaking done, but it seems to work much better than the old system.

**Comment by Joe91** [comment]
I think this can also be activeded in the gamemode Conquest. Will try that.

**Comment by Joe91** [comment]
Atm this is only enabled for infantery-bots.

**Comment by Joe91** [comment]
think I will close this for now. If you have any feedback on this, just reopen it or text me directly!

**Comment by koopa990** [comment]
> think I will close this for now. If you have any feedback on this, just reopen it or text me directly!

Just tested this out. I am uncertain if this made any difference. But this still does not change bots that wonder off in the opposite direction of where this path was supposed to be one-way to next stage of MCOMs
