### ISSUE TITLE
Bot stuck defib

### ISSUE THREAD

**Issue by koopa990** [Joe91/fun-bots#313]
### Scope

General bot behavior

### What happened?

Upon each death, there is a chance of nearby bots with defib "cannot" revive me, thus spinning in circle until my body vanished. **Also, can you tell me if it is normal for the game to allow me to be defibbed after settling on the spawn screen?**

### What was expected?

IF they are unable to defib, they ignore me and move on.

### How can we reproduce and test it?

I believe this can happen if you die while sprinting or die on uneven surfaces, which led to me to believe corpse does not stay in one spot

### Version of fun-bots and VU?

2.8.0 dev9

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by FlashHit** [comment]
@Joe91 I think we fixed that now.

**Comment by Joe91** [comment]
On latest Dev-branch by @FlashHit
