### ISSUE TITLE
Failure to be compatible with new server command

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#319]
### Scope

Core

### What happened?

When I use the `vu.CorpseDamageEnabled` command and the module provided by bree (code below) ``lua
ResourceManager:RegisterInstanceLoadHandler(Guid("F256E142-C9D8-4BFE-985B-3960B9E9D189"), Guid("705967EE-66D3-4440-88B9- FEEF77F53E77"), function(p_Instance)
    p_Instance = VeniceSoldierHealthModuleData(p_Instance)
    p_Instance:MakeWritable()
    p_Instance.manDownStateHealthPoints = 100.0
end)
``.
Often causes vu to crash.

### What was expected?

Make it so that using this command no longer produces a crash.

### How can we reproduce and test it?

[a35e3919-7836-402c-961c-7989a5e183dc.dmp](https://github.com/Joe91/fun-bots/files/13060467/a35e3919-7836-402c-961c-7989a5e183dc.dmp)
Here's my crash report form, I just loaded the fun-bots mod

### Version of fun-bots and VU?

fun-bots2.80dev9      vu version is 20056

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Reproducable, as soon as you kill a corpse of a bot.
Sadly not fixable with fun-bots. The crash does not happen in fun-bots but in VU.
