### ISSUE TITLE
Refactor: Move the 'fun-bots-helper' to a repo and add as a submodule

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#322]
The 'fun-bots-helper' should be moved off this repository and moved to a new repository and be added as a submodule to this repo. The repository should be part of the `Joe91` namespace.

**Comment by Joe91** [comment]
I like submodules, but I don't know of any solution how you can download the code (or the artifact of a release) that includes the submodule as well. Do you know if this is possible?
