### ISSUE TITLE
seine crossing bots pool party (stuck)

### ISSUE THREAD

**Issue by toba-zz** [Joe91/fun-bots#324]
### Scope

General bot behavior

### Enhancement

Remove path in seine crossing

### Use case

In middle of fight bots decide make pool party
https://youtu.be/rZft9fDr8SI

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Joe91** [comment]
Doesn't happen for me on default settings at the current dev-3 Version of V2.9. What settings and amout of bots are you using when having this issue?
