### ISSUE TITLE
Is this really how it suppose to be ? Probably a bug

### ISSUE THREAD

**Issue by mostfurious** [Joe91/fun-bots#336]
### Scope

Vehicle bot behavior

### What happened?

Yello,
I think there are still issues with bot balance. Even tho there are the same amount of players on both teams. Enemy team, without serious player interaction easily wins and takes all objectives.
But the main problem is ENEMY bots spawn in your vehicles. 

Link to the youtube video: [https://youtu.be/uIfHcMNA6CM](url)

### What was expected?

If possible better bot balance and enemy bots should not spawn on you

### How can we reproduce and test it?

Take enemy vehicle and enemy bots will spawn on you

### Version of fun-bots and VU?

2.8.0

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [ ] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
should be fixed in 2.9.

**Comment by mostfurious** [comment]
Thanks! Will try it.
