### ISSUE TITLE
Stationary AA broken since 2.7.1-Release

### ISSUE THREAD

**Issue by MatiasPastori** [Joe91/fun-bots#344]
### Scope

Core

### What happened?

The Stationary  AA for both teams is broken, just simply spinning forever and occasinally firing some rounds if by any chance you or other enemy is right in front of the cannons when its rotating.

on 2.7.1-Release it was working as inteded. 

### What was expected?

They actually targetting enemies or Aircrafts in the sky, not just spin.

### How can we reproduce and test it?

Can try this out on any map with AA, Caspian border, Desert, Kharg, etc.

### Version of fun-bots and VU?

2.7.1-Release was the last release version where this was working, don't know exactly at which point did this break. 

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Joe91** [comment]
Should be fixed on dev. Thanks a lot for this finding!
