### ISSUE TITLE
spawnInBothTeams = true not working correctly?

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#35]
I am going off the presumption that the config option spawnInBothTeams = true is meant to distribute the BOTs spawned by default into both teams. If this is the case then it doesn't.

If I set the config to spawn 30 BOTs by default then all but 1 will spawn on the enemy team and only the 1 BOT on my team. I would expect 15 to spawn on each team.

**Comment by Joe91** [comment]
Depends on the spawnmode. Which spawnmode have you selected?

**Comment by SmartShots** [comment]
spawnMode = 'increment_with_players'

I'm pretty sure the BOT didn't move on me spawning but it seems I can't test it again now because with the latest build it's not happening. Now all 30 BOTs are spawning in the enemy team.

**Comment by SmartShots** [comment]
Update - I just had it happen with a default of 5 BOTs, 4 spawned on the opposite team and 1 spawned on my team. When I spawned the BOT on my team got kicked, not moved to the other team. So now there is me vs 4 BOTs.

**Comment by SmartShots** [comment]
Just tried with the latest master (1.6.1.3) and with a default of 10 BOTs spawning 1 BOT initially spawned on the same team as me and the other 9 on the opposite team. When I spawned the 1 BOT on my team was moved to the other team as well, so all 10 BOTs were on the other team.

**Comment by Joe91** [comment]
As on round-start there are some really strange things happening to the team-ids, there is currently no other way to do this. So I would suggest to close this issue. But maybe you find a better solution ;-)
I already tried a lot to make this work.

**Comment by SmartShots** [comment]
Understood, no problem.
