### ISSUE TITLE
F12 GUI interface cannot save the sethings to config.lua profile

### ISSUE THREAD

**Issue by Defenesesword** [Joe91/fun-bots#36]
Im afraid that "record traces" have the same problem...and im not sure if it is the system permission problem(since everything "have to" run as the fxxking Administrator hh)
for example I change this function to '2' and click "save"(yes,save,not"temp... save"):
![image](https://user-images.githubusercontent.com/38837698/108542350-96bb4300-731e-11eb-82c2-a2bf3984f5e4.png)

theoretically this line should be ：
maxReconBots = 2,				-- maximum number of Bots with Recon Kit
howerver when i open the config.lua :
maxReconBots = -1,				-- maximum number of Bots with Recon Kit
Never changed...

**Comment by Joe91** [comment]
The Config.lua cannot be written. Its used for defauts and we register changes to the file. Every Data is saved in the mod.db. If you load the mod again and go to settings, the maximum Recon Bots should appear there with two, after you have saved the settings.

**Comment by Defenesesword** [comment]
Okay,Roger that,thanks a lot
