### ISSUE TITLE
Bots wont spawn

### ISSUE THREAD

**Issue by METALFINGERSDOOM** [Joe91/fun-bots#37]
every time when map reset  / changes the mod fails to load the db and shows 0 paths loaded, after few restarts it manage to load them and shows 6 paths loaded,

have to mess with it every time the round start...
also settings are not parament saved

**Comment by Joe91** [comment]
What Version of the Mod do you use?
What other Mods do you use?
Have you changed some settings?
In 1.6.1.2 there was a bug that could cause such a behavior....

**Comment by Joe91** [comment]
Since there is no reaction: Close this issue.
