### ISSUE TITLE
Suggestion - Varied BOT settings

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#43]
Would it be possible to add varied BOT settings for:

botAimWorsening
BotSniperAimWorsening
fovForShooting
botAttackMode
aimForHead
botFirstShotDelay

You could do it in the config.lua like this:

	-- BOT Settings 1
        First lot of settings here.

	-- BOT Settings 2
        Second lot of settings here.

	-- BOT Settings 3
        Third lot of settings here.

	-- BOT Settings 4
        Fourth lot of settings here.

Then have the BOTs use them like this:

BOT 1 - Uses BOT Settings 1
BOT 2 - Uses BOT Settings 2
BOT 3 - Uses BOT Settings 3
BOT 4 - Uses BOT Settings 4
BOT 5 - Uses BOT Settings 1
BOT 6 - Uses BOT Settings 2
BOT 7 - Uses BOT Settings 3
BOT 8 - Uses BOT Settings 4

...and so on.

This way we can introduce a varied level of expertise rather than all of the BOTs having to be the same level. This would make them feel more natural/human.

**Comment by Bizarrus** [comment]
A same Idea i had already for the Zombie mod with various settings. I think, we will implement these in the future.

**Comment by Joe91** [comment]
I added a random skill to the bots, that varies the aiming and reaction per bot...
Is this a solution that solves this?
