### ISSUE TITLE
BOTs attacking players in air vehicles with standard weapons.

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#46]
I noticed in Conquest that the BOTs are firing their standard weapons at enemy players in the air vehicles.

I would suggest that a check needs putting in place that if the enemy player is in a Jet or Attack Helicopter then don't bother firing at them unless the BOT has a stinger. If the BOT does have a stinger then switch to that and fire that at the enemy.

**Comment by Joe91** [comment]
Working on this rn. Will soon be added.
