### ISSUE TITLE
Traces doesn't load

### ISSUE THREAD

**Issue by zmifsx** [Joe91/fun-bots#50]
Am using smart nodes branch. 
The bots won't spawn etc bcs theres no traces. If I try to record trace it will says "Recording trace 0".

This doesnt happen with master branch.

**Comment by Joe91** [comment]
The recording-process changed a lot and is not that user friendly rn.
There are no real diffs between smart_nodes and master anymore, so what versions are you using?
Have a look at:
https://github.com/Joe91/fun-bots/blob/master/traces.md
Far from finished, but at least it shows the process of saving...
I record traces very often (including yesterday on both branches) without any problem, except the usability ;-)

**Comment by Joe91** [comment]
No answer, close issue.
