### ISSUE TITLE
Suggestion - Bots only attack armor with rockets, grenades or explosives

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#53]
If possible, bots should identify vehicle type, and if type = (APC or Tank), then only fire at it with rockets or grenades.

Maybe GreatApo's suggestions here can be used to identify vehicle type/name:
https://community.veniceunleashed.net/t/vehicle-information/2803/2

**Comment by MoxUK** [comment]
maybe GreatApo's suggestions here can be used to identify vehicle type/name:

https://community.veniceunleashed.net/t/vehicle-information/2803/2

**Comment by Joe91** [comment]
Its already done. If you have engineers, they will use the RPGs as soon as you are in a vehicle. But I can let the other classes throw grenades as well...

**Comment by MoxUK** [comment]
I believe a frag will do a small amount of damage to armoured vehicles; 40mm GL do a bit of damage as well.

Problem currently is that e.g. bot not equipped to take on a tank or APC still attack with rifles and effectively give themselves away. It's logic to a bot to attack (any) target, but for a real player, it would considered instant suicide.

Alternative solution would be (in pseudocode):
If equipped with RPG, attack armoured vehicle,
else move opposite direction/find cover.

**Comment by Joe91** [comment]
I tried a LAV with 20 bots all throwing grenades at the vehicle. No damage at all... :-/
But maybe I just let them Ignore the vehicles. What behaviour would you suggest if a player is in a vehicle? Run to cover is not possible yet ^^

**Comment by MoxUK** [comment]
I don't know how advanced it's possible to make the bots or how much effort it will take, so these might be unrealistic but:

If vehicle type = [tank, APC] and vehicle occupied by enemy
   {
   If Bot equipment includes RPGs, then attack with RPG
   else 
   If Bot equipment does not include RPGs, then run away (reverse travel direction of path?) - OR - ignore vehicle
   }

If vehicle type /= [tank, APC] and vehicle occupied by enemy
   { 
    If Bot equipment does includes RPGs, then attack with RPG
    If Bot equipment does not include RPGs, then attack vehicle with primary weapon
   }

If this is too much of a pain, then I expect ignore or reverse path would be an acceptable alternative.

**Comment by lywit** [comment]
The HUMVEE can be damaged by grenades. I would do it the way that MoxUK suggests but also add logic for throwing grenades at Humvees and similar armored cars in the game.

**Comment by Joe91** [comment]
I made the bots choose the way they attack vehicles depending on the vehicle and their loadouts. Otherwise they just ignore the vehicle. This is in Version 1.7.0.10.
Still some testing needed, but a first look seemed quite promissing...
