### ISSUE TITLE
Conquest - Bots spawn randomly at map not following standard spawn rules

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#54]
Noticed this on Karkand vs 2 bots playing Conquest Asault: having control of all points (A-E), I had a bot (without any other bots nearby) spawn on D; killed the bot and immediately having the second bot spawn where the first one had appeared.

Expected:
Bots will follow spawn rules of "spawn on controlled point, squad mate/leader"

**Comment by Joe91** [comment]
I haven't had a look at assault more closely. I will have a look at this gamemode. Conquest should work with the spawn-rules.
So the Bots spawned on an enemy flag? Isnt assault finished as soon as all objectives are taken?
If they have nothing left to spawn on, they just spawn randomly anywhere...

**Comment by MoxUK** [comment]
"If all flags are captured by the attacking team, the defending team will only be able to spawn on their squad mates until a flag is taken back. " (from BF3 wiki) so technically the round should have been over as there were not bots alive and all flags had been capped, so you're correct: They seem to spawn randomly after that.

**Comment by Joe91** [comment]
Ah okay. Then I just have to disable spawning when there is no valid option left for then to spawn. Thanks for that information!

**Comment by Joe91** [comment]
I disabled the random-spawn in conquest and rush. In Version 1.7.0.10 this should not happen anymore. If you find anything not working correctly just let me know :-)
