### ISSUE TITLE
How to use Chat-Commands?Menu display is not normal

### ISSUE THREAD

**Issue by hereww** [Joe91/fun-bots#55]

**Comment by MajorVictory** [comment]
Chat commands are disabled by default. You can re-enable them two ways:
1. Edit the file `ext/Shared/Config.lua` and change the value `disableChatCommands` to `false`
2. You can enable them from the in-game menu by opening the Fun-Bots menu (F12) going to Settings (F10) navigate to the "Other" tab (the last tab) and change the first option, "Disable Chat Commands", to `No`

**Comment by Joe91** [comment]
Could you please add some more information? Or is your issue solved with this answer?

**Comment by Joe91** [comment]
No reaction. No known issue
