### ISSUE TITLE
v.1.7.0.13 - No-PreRound causes bots to be inactive and fail to respawn (v.1.7.013)

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#56]
The No-PreRound mod issue is back in v.1.7.0.13, i.e bots remains inactive and when killed, they do not respawn.

**Comment by MoxUK** [comment]
update No-PreRound to latest version (1.0.1) but it didn't change anything regarding Funbots

**Comment by Joe91** [comment]
What map and gamemode? I had no issues with the No preround Mod in this Version yet?

**Comment by Joe91** [comment]
Update: If you have the mod NoPreRound before the fun-Bots-Mod in you modlist, it does not work. If fun-bots is above, it causes this error

**Comment by MoxUK** [comment]
Tried it on Karkand, Gulf, Caspian, Riverside, Railroad - all on Conquest small (except Karkand which was on Assault).

I will check if Funbots are above No-Preround and retest.

Thanks, Joe.

**Comment by MoxUK** [comment]
Verified...Put funbot as the first mod to load and not seeing the issue any more.
Closed as not an issue

**Comment by Joe91** [comment]
I think this is still an issue as there should be no dependency on the order of the List ^^

**Comment by Joe91** [comment]
Now I use the Modlist for detection. Should work this time ^^ V1.7.0.15
