### ISSUE TITLE
Error trace in VU console (v.1.7.013)

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#57]
Ran a game vs. bots on Gulf of Oman and noticed the console for the VU server was filled with an error from Funbots:
[string "Bot.lua"]:422: Attempted to access a destroyed player object.stack traceback:[C]: in metamethod 'index'[string "Bot.lua"]:422: in method '_updateAiming'[string "Bot.lua"]: ...

(sorry, that's all I can see in my console and I don't have a log with more details - see attached screenshot),

![image](https://user-images.githubusercontent.com/81385159/113520761-57267e80-958d-11eb-8487-a74b7fbcd163.png)

**Comment by Joe91** [comment]
What gamemode were you using and have you played some maps before?
If this reproducable?

**Comment by MoxUK** [comment]
Conquest small on Gulf of Oman. It was the second map on my playlist.
Happened on point A (playing as US forces).

Have not been able to reproduce, so close for now and I'll re-add if I observe it again.

**Comment by Joe91** [comment]
I think I might have found something that could case this. Did you play on an open server?

**Comment by MoxUK** [comment]
Locked server - only me vs. 4 bots

**Comment by Joe91** [comment]
I created a version 14 which may fix this issue. Would you mind to switch to this version?

**Comment by Joe91** [comment]
I think its fixed. If it happens again, just reopen it ;-)
