### ISSUE TITLE
Suggestion: Delayed firing of smaw/rpgs from Bots

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#58]
Noticed that the time it takes the bots to switch to the smaw/rpg and fire is extremely fast and doesn't emulate an aimed shot.
Most players equips the weapons then takes a short time to aim before firing, whereas the bot seems to fire the microsecond the weapon is selected.

Allow a delay (maybe make it a separate value) to emulate an aimed shot.

**Comment by MoxUK** [comment]
sorry, above was incorrect.
It should have said "he time it takes the bots to switch to the smaw/rpg and fire is extremely FAST"

**Comment by Joe91** [comment]
I added the default-first-shot delay on weapon-switch to rpg...

**Comment by Joe91** [comment]
Since no further feedback I will close this.
