### ISSUE TITLE
Suggestion: Bots are now too passive vs choppers (v.1.7.013)

### ISSUE THREAD

**Issue by MoxUK** [Joe91/fun-bots#59]
Bots are now extremely passive when it comes to shooting at the chopper, for example:
Coming in at low altitude and low speed in the Viper, no bots are shooting except for the engineer that fires rockets at you.
You can literally land right in front of a bot and he won't shoot at you and will only attack when he is so close he will try to knife the chopper.

Regular firearms can do plenty of damage to the chopper due to the low protection of pilot and passanger.
A good sniper will regularly shoot the pilot out of a low flying chopper which I have had a bot emulate - this sadly doesn't seem to happen any more.

**Comment by Joe91** [comment]
Thanks for this information.
The vehicle handling is new and not optimized at all yet. Should they attack all close air vehicles with rifels?
I can change this easily.

**Comment by MoxUK** [comment]
I would say attack all choppers with rifles as well.

Jets are in general too fast to attack (although vs. real players you will see the occasional pilot sniper kill or RPG kill) so maybe not let the bots bother with those?

**Comment by Joe91** [comment]
I added this in V14. Can you try this out and tell me if you are happy with the behaviour?

**Comment by MoxUK** [comment]
Works like a charm now...Thanks, Joe
