### ISSUE TITLE
In Noshahr Canals TDM bots simply dosen't sprint.

### ISSUE THREAD

**Issue by ThaigoLOCAO** [Joe91/fun-bots#60]
In Noshahr Canals TDM bots simply dosen't sprint, and some of then spawn in water.

**Comment by Joe91** [comment]
The paths are very old and so Not include these information. If you want you can record new ones...

**Comment by ThaigoLOCAO** [comment]
> The paths are very old and do not include these information. If you want you can record new ones...
> As some paths Go trough the water the Bots also spawn there.

Okay, got it, I gotta try to do it, thanks.

**Comment by GaryTheNoTrashCougar** [comment]
Open the mod.db file using a database tool e.g. DB Browser for SQLite.  Change inputVar from 3 to 4.  To save time just paste - UPDATE MP_017_TeamDeathMatch0_table SET pathIndex = 4 WHERE pathIndex = 3;  into Execute SQL.  Hope this helps.

**Comment by Joe91** [comment]
This way they would all just sprint. If this is what you want, you can also overwrite the move-mode with the settings to 4.
But to get realistic behaviour new paths should be recorded. I can do this as well when I have some time, but I am focused on other priorites atm :-)
But if you record some new traces, you can send me the mod.db and I can merge them on the master-branch...

**Comment by ThaigoLOCAO** [comment]
I'm sorry for delay, I was pretty busy these days. 
I'm recording some paths to Noshahr Canals and sure I can send to you, will be a pleasure.

**Comment by Joe91** [comment]
No Problem at all! If you need any help (more than the trace.md file) then just let me know :-)

**Comment by Joe91** [comment]
I close this issue. If I find some time I will add some new paths to this map...
