### ISSUE TITLE
When try to running at 30 or 60hz, the server crash 

### ISSUE THREAD

**Issue by YuuMJ** [Joe91/fun-bots#61]
When try to running at 30 or 60hz, the server crash

**Comment by Bizarrus** [comment]
Please provide more informations.

> Used mods
> Computer (Memory, CPU,..)
> Already tried to run the server without mods?
> Already tried to disable single mods?

**Comment by YuuMJ** [comment]
> Please provide more informations.
> 
> > Used mods
> > Computer (Memory, CPU,..)
> > Already tried to run the server without mods?
> > Already tried to disable single mods?

Server crash when running at 30 or 60hz server after 1h, 120Hz server does not have this problem.
Used mods :MedicRadar, vu-mapvote, fun-bots-1.7.0.18, Killfeed-2.0, VU-Loading
Computer:  (running in a virtual machine, a 48 Core AMD EPYC processor allocate 4 cores, 8 gig mem)
Already tried to run the server without mods? (Yes, the server running pretty well)
Already tried to disable single mods? (Yes, still crash after 1h running)

**Comment by Joe91** [comment]
Thanks for this information and sorry for the delayed reaction... A few more questions:
- Does this happen no matter if the server is played on or not?
- Is it exactly an hour or just about an hour?
- If it only happens while played on it: Is it on a special even? (for example map-switch)?

**Comment by YuuMJ** [comment]
> Thanks for this information and sorry for the delayed reaction... A few more questions:
> 
> * Does this happen no matter if the server is played on or not?
> * Is it exactly an hour or just about an hour?
> * If it only happens while played on it: Is it on a special even? (for example map-switch)?

I recently tested it again, and it probably wasn't due to server frequency issues
I found that the server crashed when there were more than 13 human players, and the 14th player is connecting the server
The maximum players of my server are 64
here is my funbot settings:

MAX_NUMBER_OF_BOTS	= 28;			-- maximum bots that can be spawned
USE_REAL_DAMAGE 	= true;			-- with real damage, the hitboxes are a bit buggy
BOT_TOKEN			= "BOT_";		-- token Bots are marked with

Config = {
	--global
	botWeapon = "Auto",			-- Select the weapon the bots use
	botKit = "RANDOM_KIT",			-- see BotKits
	botColor = "RANDOM_COLOR",		-- see BotColors
	zombieMode = false,				-- Zombie Bot Mode

	--difficluty
	botAimWorsening = 0.8,			-- make aim worse: for difficulty: 0 = no offset (hard), 1 or even greater = more sway (easy).
	botSniperAimWorsening = 0.4,	-- see botAimWorsening, only for Sniper-rifles
	damageFactorAssault = 0.3,		-- origninal Damage from bots gets multiplied by this
	damageFactorCarabine = 0.3,		-- origninal Damage from bots gets multiplied by this
	damageFactorLMG = 0.3,			-- origninal Damage from bots gets multiplied by this
	damageFactorPDW = 0.3,			-- origninal Damage from bots gets multiplied by this
	damageFactorSniper = 0.8,		-- origninal Damage from bots gets multiplied by this
	damageFactorShotgun = 0.7,		-- origninal Damage from bots gets multiplied by this
	damageFactorPistol = 0.3,		-- origninal Damage from bots gets multiplied by this
	damageFactorKnife = 1.5,		-- origninal Damage from bots gets multiplied by this

	--spawn
	spawnMode = 'increment_with_players',	-- mode the bots spawn with 
	spawnInBothTeams = true,		-- Bots spawn in both teams
	initNumberOfBots = 4,			-- bots for spawnmode
	newBotsPerNewPlayer = 3,		-- number to increase Bots, when new players join
	spawnDelayBots = 10.0,			-- time till bots spawn on levelstart -- OBSOLETE
	botTeam = TeamId.Team2, 	-- default bot team (0 = neutral / auto, 1 = US, 2 = RU) TeamId.Team2
	botNewLoadoutOnSpawn = true,	-- bots get a new kit and color, if they respawn
	maxAssaultBots = -1,			-- maximum number of Bots with Assault Kit
	maxEngineerBots = 12,			-- maximum number of Bots with Engineer Kit
	maxSupportBots = -1,			-- maximum number of Bots with Support Kit
	maxReconBots = 3,				-- maximum number of Bots with Recon Kit

	-- weapons
	useRandomWeapon = true,			-- use a random weapon out of the class list
	assaultWeapon = "M416",		-- weapon of Assault class
	engineerWeapon = "M4A1",		-- weapon of Engineer class
	supportWeapon = "M249",			-- weapon of Support class
	reconWeapon = "L96_6x",			-- weapon of Recon class
	pistol = "MP412Rex",			-- Bot pistol
	knife = "Razor",				-- Bot knife
	assaultWeaponSet = "Custom",	-- weaponset of Assault class
	engineerWeaponSet = "Custom",	-- weaponset of Engineer class
	supportWeaponSet = "Custom",	-- weaponset of Support class
	reconWeaponSet = "Custom",		-- weaponset of Recon class

	-- behaviour
	fovForShooting = 200,			-- Degrees of FOV of Bot
	maxRaycastDistance = 150,		-- meters bots start shooting at player
	maxShootDistanceNoSniper = 120,	-- meters a bot (not sniper) start shooting at player
	botAttackMode = "Random",		-- Mode the Bots attack with. Random, Crouch or Stand
	shootBackIfHit = true,			-- bot shoots back, if hit
	botsAttackBots = true,			-- bots attack bots from other team
	meleeAttackIfClose = true,		-- bot attacks with melee if close
	botCanKillHimself = false,		-- if a bot is that close he will attack, even if not in FOV
	botsRevive = true,				-- Bots revive other players
	botsThrowGrenades = true,		-- Bots throw grenades
	botsDeploy = true,				-- Bots deploy ammo and medkits
	deployCycle	= 50,				-- time between deployment of bots

	-- traces
	debugTracePaths = false,		-- Shows the trace line and search area from Commo Rose selection
	waypointRange = 100,			-- Set how far away waypoints are visible (meters)
	drawWaypointLines = true,		-- Draw waypoint connection Lines
	lineRange = 15,					-- Set how far away waypoint lines are visible (meters)
	drawWaypointIDs = true,			-- Draw waypoint IDs
	textRange = 3,					-- Set how far away waypoint text is visible (meters)
	debugSelectionRaytraces = false,-- Shows the trace line and search area from Commo Rose selection
	traceDelta = 0.3,					-- update intervall of trace

	-- advanced
	distanceForDirectAttack = 5,	-- if that close, the bot can hear you
	maxBotAttackBotDistance = 30,	-- meters a bot attacks an other bot
	meleeAttackCoolDown = 3.0,		-- the time a bot waits before attacking with melee again
	aimForHead = false,				-- bots aim for the head
	jumpWhileShooting = true,		-- bots jump over obstacles while shooting if needed
	jumpWhileMoving = true,			-- bots jump while moving. If false, only on obstacles!
	overWriteBotSpeedMode = 0,		-- 0 = no overwrite. 1 = prone, 2 = crouch, 3 = walk, 4 = run
	overWriteBotAttackMode = 0,		-- Affects Aiming!!! 0 = no overwrite. 1 = prone, 2 = crouch (good aim), 3 = walk (good aim), 4 = run
	speedFactor = 1.0,				-- reduces the movementspeed. 1 = normal, 0 = standing.
	speedFactorAttack = 0.6,		-- reduces the movementspeed while attacking. 1 = normal, 0 = standing.

	-- expert
	botFirstShotDelay = 0.35,		-- delay for first shot. If too small, there will be great spread in first cycle because its not kompensated jet.
	botMinTimeShootAtPlayer = 2.0,	-- the minimum time a bot shoots at one player
	botFireModeDuration = 5.0,		-- the minimum time a bot tries to shoot a player
	maximunYawPerSec = 450,			-- in Degree. Rotaion-Movement per second.
	targetDistanceWayPoint = 0.8,	-- distance the bots have to reach to continue with next Waypoint
	keepOneSlotForPlayers = true,	-- always keep one slot for new Players to join
	distanceToSpawnBots	= 30,		-- distance to spawn Bots away from players
	heightDistanceToSpawn = 2.5,	-- distance vertically, Bots should spawn away, if closer than distance
	distanceToSpawnReduction = 5,	-- reduce distance if not possible
	maxTrysToSpawnAtDistance = 3,	-- try this often to spawn a bot away from players
	headShotFactorBots = 1.0,		-- factor for damage if headshot
	attackWayBots = true,			-- bots on paths attack player
	respawnWayBots = true,			-- bots on paths respawn if killed

	-- UI settings & language options
	disableUserInterface = false,	-- if true, the complete UI will be disabled (not available in the UI ;-) )
	disableChatCommands = true,	 	-- if true, no chat commands can be used
	disableRCONCommands = true,	 	-- if true, no RCON commands can be used
	traceUsageAllowed = true,		-- if false, no traces can be recorded, deleted or saved
	settingsPassword = "homo123456",		-- if nil, disable it. Otherwise use a String with your password
	language = nil, --"de_DE",		-- de_DE as sample (default is english, when language file doesnt exists)
};

--don't change these values unless you know what you do
StaticConfig = {
	traceDeltaShooting = 0.4,			-- update intervall of trace back to path the bots left for shooting
	raycastInterval = 0.05,				-- update intervall of client raycasts
	botAttackBotCheckInterval = 0.05,	-- update intervall of client raycasts
	botUpdateCycle = 0.1,				-- update-intervall of bots
	botAimUpdateCycle = 0.05,			-- = 3 frames at 60 Hz
	targetHeightDistanceWayPoint = 1.5	-- distance the bots have to reach in height to continue with next Waypoint
};

**Comment by Joe91** [comment]
Thanks for all this information!

@MajorVictory could this be related to the amount of NetEvents we send? With every player we send more events. Once for the attacking and then for the Bot on Bot attack as well...
Tbh I never played with that many people but this might get really heavy for the server...

**Comment by YuuMJ** [comment]
Thank you very much for your reply and I apologize for my poor english

This issue can it be resolved in a future update?
Or is there a way to limit the number of human players under 13?

**Comment by Joe91** [comment]
You can try if this still happens, if you reduce the Bot on Bot update-Cycle and maybe even the nomal update-cycle in the Config.lua in the Section "staticConfig"
	raycastInterval = 0.05,				-- update intervall of client raycasts
	botAttackBotCheckInterval = 0.05,	-- update intervall of client raycasts
	
If you change the second one to 0.2 and the first one to 0.1 for example...
Do you play with bots in both teams?

**Comment by YuuMJ** [comment]
> You can try if this still happens, if you reduce the Bot on Bot update-Cycle and maybe even the nomal update-cycle in the Config.lua in the Section "staticConfig"
> 
> ```
>         raycastInterval = 0.05,				-- update intervall of client raycasts
>         botAttackBotCheckInterval = 0.05,	-- update intervall of client raycasts
> ```
> 
> If you change the second one to 0.2 and the first one to 0.1 for example...
> Do you play with bots in both teams?

Just spawn bot in enemy team, no friendly bots

**Comment by Joe91** [comment]
Have you found out a little more?
