### ISSUE TITLE
Suggestion - Squad Deathmatch

### ISSUE THREAD

**Issue by GaryTheNoTrashCougar** [Joe91/fun-bots#62]
Would it be possible to add teams 3 & 4?  Maybe a 'Squad Teams' spawn mode?  If not does anyone here know how to change the UI for SDM to TDM?  Also, I have attached paths recorded for all maps if anyone is interested.  Thanks.
[mod.zip](https://github.com/Joe91/fun-bots/files/6354451/mod.zip)

**Comment by Joe91** [comment]
So you recorded paths for all Squad-DM-Maps?? WOW!
I can have a look at this. In the new UI there might be the spawn in any team already in.
I will have to add this as gamemode and find out what it takes to make this work. What happes right now, if you use your paths?

**Comment by GaryTheNoTrashCougar** [comment]
It just plays like TDM, I can only get bots to spawn in 2 of the squads though.  With the UI I meant things like the scoreboard.  Obviously the other two teams are empty & it only shows 4 players/bots on each team, even though you can have more.  My thought was if it wasn't possible to make the bots spawn in the other teams, maybe it would be possible to basically convert SDM into TDM by changing the scoreboard etc. (https://github.com/EmulatorNexus/Venice-EBX/tree/f06c290fa43c80e07985eda65ba74c59f4c01aa0/UI/Flow/Screen/Scoreboards).  As for how to make the bots spawn in all teams, you probably just need to add teams 3 & 4 as opposing teams in BotManager, as only teams 1 & 2 are referenced.  Also add a spawn mode like 'balanced_teams' with team 3 & 4 included to BotSpawner.

**Comment by Joe91** [comment]
Thanks for your reply. I will have a look at the gamemode and hope to support it by the weekend. I will let you know, so you can test it...

**Comment by Joe91** [comment]
You can have a look at the "squad-dm" branch. First kind of working version I think...

**Comment by Joe91** [comment]
by the way: @GaryTheNoTrashCougar Your paths are really great! Just tried them a little and merged them all into the database-file. Thank you very much for all your work!!

**Comment by GaryTheNoTrashCougar** [comment]
No... thank you!!  Your work is amazing.  I'll take a look now.

**Comment by Joe91** [comment]
Sadly there is this issue in VU:
https://github.com/EmulatorNexus/VeniceUnleashed/issues/578
So right now all the russian-squads have no squad assigned to them.

**Comment by GaryTheNoTrashCougar** [comment]
OK.  Hopefully they will fix this.  I've just had a quick play.  I was in alpha squad, US side, seems non of the other squads fight each other, only fighting my squad but not attacking me either.  Is this related to this issue?

**Comment by Joe91** [comment]
Strage. They did when I tried it... I will check it again... Maybe I missed something.
What spawn-mode did you use? Have only tested with the balanced team yet...

**Comment by GaryTheNoTrashCougar** [comment]
Yes balanced teams

**Comment by Joe91** [comment]
I will let you know, when I'm done with testing and found out why...

**Comment by Joe91** [comment]
They just checkt bots from the same team most of the time. Now they should attack normal again. I will have a look at the spawnmodes more closely now...

**Comment by Joe91** [comment]
I think it now starts to get playable...
What do you think about the spawn-modes? Should we reduce the calulated amout per team by the half in Squad-Death-Match?

**Comment by GaryTheNoTrashCougar** [comment]
I would only play with 4 in each squad.  With initNumberOfBots 8 they only spawned in first 2 squads but all when set to 4.

**Comment by Joe91** [comment]
Hmm. I knw what you mean, but I have to think a little about how to implement this. Maybe I will add a separated value like "maxBotsPerTeam" that limits the amount per team in SDM...

**Comment by GaryTheNoTrashCougar** [comment]
Can you not just override config.initNumberOfBots if gametype is Squad DM?

**Comment by Joe91** [comment]
Overwriting the config-values is no option (causes inconsistence between client and server), but I can ignore them or use some other values in this case.

**Comment by GaryTheNoTrashCougar** [comment]
How about maxBotsPerTeamSDM & maxBotsPerTeamTDM variables, that way you could have both gamemodes running on a server without having to change settings?

**Comment by Joe91** [comment]
Yeah, that would do it.
Have you tried the Gameplay again? Anything not working as wanted?

**Comment by GaryTheNoTrashCougar** [comment]
Works great, thank you.  There are a few things unrelated to this if you are interested.  I don't know if player spawns are in any way influenced by enemy bot positions, but quite often (mostly in TDM) player spawns are in paths of enemy bots.  Would be cool if we could remove all refences to vanilla spawn entity data & create our own through the path editor so player spawns could avoid bot paths.  The other thing was to do with bots shooting back when hit.  Would be nice if there was a delay that is scaled by distance if that is possible.  Sorry if I seem demanding, just some ideas I had.

**Comment by Joe91** [comment]
Good Ideas! I will have a look at. Always happy on feedback how to improve the bots ;-)

**Comment by Joe91** [comment]
I made a rework for the Squad-Bug. Now all teams have a vailid squad...

**Comment by Joe91** [comment]
I will close this for now and continue with improving on it from time to time. The team-limit vars are available now...
