### ISSUE TITLE
Bots no longer appear in Gun Master games

### ISSUE THREAD

**Issue by Swagger200** [Joe91/fun-bots#72]
I am using the vanilla 1.7.15

**Comment by Joe91** [comment]
Thank you for this report! This is right and already fixed on the master_V2 branch and will soon be merged back into a new master. In the meantime I would recomend to go back to 1.7.0.19 or if you can life with other potential bugs just use the branch master_V2

**Comment by Joe91** [comment]
fixed in 2.0.0.0
