### ISSUE TITLE
vehicle balancing with fixed Bot spawn mode

### ISSUE THREAD

**Issue by Dontavolta** [Joe91/fun-bots#73]
strengthen the bots presence on conquest and rush per player recounting bot spawn on respective teams

2 solutions
from current players team, remove 2 to make space for endless players, too
from side not declared bot team default. remove 2

optionally  under fixed spawn, bots per player.

**Comment by Joe91** [comment]
There already is a "increment_with_player" spawn-mode.
But I added a factor for the balanced-team-mode and fixed player-count. I just pushed this on the master.

**Comment by Joe91** [comment]
If you are not happy with this solution, just let me know...

**Comment by Dontavolta** [comment]
great. ty.
