### ISSUE TITLE
Conquest bot spawn and aim performance factor

### ISSUE THREAD

**Issue by Dontavolta** [Joe91/fun-bots#78]
Edit: new chapters **aim performance** on 2.6.2021:
bot performance fov efficiency aim mapping
further bot performance options
restructured performance 

### Spawnmode fix: 

The spawnmode keep_player count seems to cause crash when players fill 1 team completely.
 Please update keep_playercount

if you can reproduce the issue or see fit
 a if possible disable botspawn and teambalancing on us team at some point. 
 b kick bots on the full side when one or both teams overflow with real players.
 c limit (real) players
 
 
 
 
Request; I find it fit to ask to prioritize conquest players for more casual players in vu and the server after all its battlefield.

Option b looked natural, but i cant judge the difficulty. in my eyes it allows real Player Overflow stabilize for servers with auto spawnmode keep_playercount opened towards high player numbers

### Idea  1
hotfix kick bots who dont find a spawn after 10 seconds. Check to add bots time limit 20 seconds

Encompassing any of the following "the chosen team overflow status script" when override for spawnmmode is implemented and activated by running parts of the test for space on the teams to reactivate spawnmode from manual every now and then.

reset spawnmode = keep_playercount

### Idea 2
On the start of the script add player count, kick the full team and changing to manual asap, "easy" or "full", and a live_override test and set mode to manual and balancing back on if low enough

On the < easy > way & effective player-count-keeping runs until spawnplayerlimit can be reached /2 -1, here the number of real players on the server is measured to potentially disrupt the game.
here players from 1 team would keep playing players and bots asymmetrically always.

The trigger for stabilizing to manual could look like this
if ( real_players_count   <<  player_count(( spawnmode_players_limit    /    2 ) -1 ) 
&& (real_players_count    <<     player_count( spawnmode_players_limit) )
== false
spawnmode(manual)

### Idea 2b
On <full> the teams are monitored closely by the mod. With < full > there is a spawnmode on the teams until both have to be deactivated. The teams bots get kicked one after the other but only if they are full of players.

until spawnplayerlimit -2 only disruptions to the server  -  full teams are recognised and compensated.

--  Implementation constructions of some steps in order of appearance and no relation to eachother other than the apparent.

### Idea 2 

$$ counting teamlimits for bots on each team
[...]
[...]

count_real_players(int)
##set 
int teamlimit 
##to
teamlimit =spawmode_player_limit / 2

when new real_player joins
{

$$So both teams run a real player count based trigger

boolean playerslimitreached
int 123 
123= 1
for 123    <<    2

{
newplayer_ID() player_joins() or real_player_teamchanges() ---     trigger
if (team_count_ID(123)   ==    teamlimit -1

{
{
kick_bots_team_ID(123)
123=123+1
}

### Idea 2b

$$count real players in team 
if ( real_players_sum()    >>    10 )
{
keep_playercount_switch()
{
team_ID() 
spawnmode_manual()
kick_bots()
count_real_players()
int i
int real_players_sum

}
i = 0

for ( i    <<    2 )          ---- kick full teams
{
team(i),
i=int
for team_ID(i)
{

if real_players_sum(i)    >>    spawnmode_limit()/2        ----lock changes in spawnmode
{
{
team_real = true
spawnmode = spawnmode_manual()
run kick_bots_teamID(i)

}

}
i = i +1

}#if

}#for

}#if

}#if

}#for

### bot performance fov efficiency aim mapping
**activate two step tracing with lower res trace print and call 
for distance over 30 or fixed to max attack distance zone2 40 -80, or vehicles and snipers.
locking fov with larger spots to aspect fov zones on bots in vehicles and snipers**

bot attack mode aspect fov alignment with longer range. 
triggered by a fake fire on a teammate got hit/ spotted him. 
method: raytracing activates a blind carbon copy shot with 100% accuracy to all others or direct damage so the bots go into fov aspect aiming. 
function random(0.4)

### further bot performance options
random() 0.5 function group prediction 
ai script moves 
1. run a 1- 5m depending on map or on contact, spin random +- 390 , triggered - timed recursive S 
offset to turn in the area to the direction by group prediction, s to straight if no contact is made. (like a robot)
2. free path to manoever
3. with attack mode: run back on trace until out of range ideally into cover

### BotServer Performance 

fov efficiency mapping
**activate two step tracing with lower res trace print and call 
for distance over 30 or fixed to max attack distance zone2 40 -80, or vehicles and snipers.
locking fov with larger spots to aspect fov zones on bots in vehicles and snipers**

bot attack mode aspect fov alignment with longer range. 
triggered by a fake fire on a teammate got hit/ spotted him. 
method: raytracing activates a blind carbon copy shot with 100% accuracy to all others or direct damage so the bots go into fov aspect aiming. 
function random(0.4)

**height differences and strategic map points for vehicles present challenges for servers in terrain especially with vehicles** 

examples: helicopters, jeeps, quads, bikes

to make bots an alert level based on hard targets map or less focussed in general while and air target is zoning them.

Such possibly a hard targets map could be a set of fixed speed and hightmap values actualised for vehicles every 20 seconds. this would give pilots a break too.

add limited attention aspects 

Add aiming filters that will ignore hard targets by smart raytracing or Reducing bot behavior-distance globally for the 2 seconds of veehicle encounter

Options for possible factors
a based heightdelta or better hightvalue map on temporarily setting attack distance to 30 for the bot who detected vertical offset, i.e. straight number bots
b based on disabling attack mode
c making air vehicles armoured
d making it invisible on raytracing because moves fast?

Alertlevel idea A
Add 2d rays filtering after starting fire with horizontal rays with 70m thickness for recognition filtering

optional
canceling raytracing too
force another ray thickness for another class

force verctical 2d raytracing for vehicles

Alertlevel idea B
based on adding a speedvalue test of the target, 

idea 2 
based on target type add speed based or hight based randomness to raytracing result to lower cpu 

ignore target.
randomized to 0.4

idea 2 B

add measure height (ideally from terrain heightmap)
add detect_vehcile()
create unfocus()

*set attack distance to 30

refreshing time for 10 seconds 
either 
randomized to 0.4

or set
increasing limitinr_vertical_aiming_bots until set_vertical_aim_limiter
idea 1

add exception for tracing process
for (raytrace() == 1 )  --- sucessful raytracing
[]

if 
{(heightmap_player_aiming 2 > heightmap_player_1 + 30)
create focus set attack distance 30 time ally for 20 seconds 
{

[]

else continue
...
random() > 0-.4

**Comment by Joe91** [comment]
You can choose the bots to only spawn in one team.
I will have a look at all these points...

**Comment by Dontavolta** [comment]
Yeah man, we tried everything only spawn on team x, but players dont like that on CQ

I run 1.7.1.4 bots

**Comment by Joe91** [comment]
In this Case please just update to V2.0.0.0 or to the latestest master_v2 branch.
V1.7.1.X is quite buggy since it was completely in our rework phase. If it still  happens in 2.0, just let me know. If you want a quite stable version, you should use 1.7.0.19.

**Comment by Dontavolta** [comment]
wow thats good news. i wil update asap. 
Should i open a new issue for other cq issues?

**Comment by Joe91** [comment]
The spawn with the base is already implemented in the current master (V2.0)
I added the factor for the balancing of the team. So this should result in always more bots in the opposite team of the players.
What do you mean with the spawn-trapping? Right now You should provide a path to every other objective from one objective. This can also be done by creating just one or two long paths, that connect all objectives. These paths should be lableled with all objectives. Then the bots can always come back to the happening of the game. This already works fine on most of the recorded maps.
If you need a little support in the recording, jsut contact me on discord, then we can chat or talk a little about it and I can improve the documentation...

**Comment by Dontavolta** [comment]
Dear Joe

there is a map i made called Alborz mountains
it has an objective E on the lake.
The bots spawn on it in heaps 
and, since it lies in the corner
they cant escape with their paths.

Similar effect on Wake Island. When the bots are on one place under attack, they dont find their way to escape bc they always see an enemy.

**Comment by Dontavolta** [comment]
we are running the second latest bot spawn logic v2.

On maps, the balance was shifted further back generally.

solution:
only spawn on bases, when  1 checkpoint is left, since it tips the balance.

**Comment by Dontavolta** [comment]
By spawntrapping i mean: 1 team holds 1 objective based on spawn delay, spawncamping and total war bot "attending and motivation"

**Comment by Joe91** [comment]
The spawn-delay of the bots is now exactly the same as a player has. But it should be possible to add a factor to it...

**Comment by Dontavolta** [comment]
nice, i suggest we look at that to control the number of bots in combat (cpu), on lost and locked down objectives and beyond.

**Comment by Firjens** [comment]
Hey, can you split this issue up in multiple issues? (One issue per bug, feature or enhancement). This allows us to appropriately link each issue to a pull request, discussions and more.
