### ISSUE TITLE
Allow the bots to use lock-on weapons (eg. JAVELIN, Stinger, etc)

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#80]
Hello, and thanks for making such an amazing plugin for Battlefield 3.

### Current situation:
Currently, bots only use grenades and RPG (or MSAW) against vehicles and vehicles.

### Suggested change:
It'd be nice to see that each engineer either spawns with a RPG-like weapon, a JAVELIN-like weapon or a Stinger-like weapon and they can use it on vehicles like players are able to do.

For RPG-like weapons, no change is requested as the way they work is good.

For the locked-on missile launchers, when a bot has an armored vehicle or other object that can be locked on using the missile launchers, they use their weapon against that vehicle by initially locking on the vehicle and firing when the lock on is completed.

- Additionally, having a time between lock-on and actual firing gives it a bit more realistic variant
- When the vehicle is getting out-of-range, the bot has to follow that vehicle but it shouldn't be too strict (example; when a plane is flying over at low altitude and is going very fast, it's more difficult to track it than when it's a helicopter flying nearby).
- A configuration to allow server owners and developers to fine-tune this, by including an option to enable or disable this, a minimum and maximum lock-on time (when a missile launcher is locked on a vehicle, having it not fire directly makes it more realistic), etc.
- A configuration to allow a maximum amount of JAVELIN and Stinger per team (if there are a maximum of 3 engineers and they all 3 have stingers, it's going to cause for a bad time for any plane).

I'll be updating this issue whenever a new change comes in mind related to this.

Thanks,
Firjen

**Comment by FlashHit** [comment]
Not sure if it’s possible since bots can‘t aim, and I think that required for the javelin

**Comment by Firjens** [comment]
> Not sure if it’s possible since bots can‘t aim, and I think that required for the javelin

A custom implementation should be possible?

**Comment by FlashHit** [comment]
> > Not sure if it’s possible since bots can‘t aim, and I think that required for the javelin
> 
> 
> 
> A custom implementation should be possible?

There is nothing we can do except waiting for VU to implement a method that lets us make players and bots aim/ scope in.

**Comment by Firjens** [comment]
Is this now possible with the new VU update?

**Comment by FlashHit** [comment]
should be, ye

**Comment by Joe91** [comment]
Should work on the latest dev-commit...
