### ISSUE TITLE
Bots respawning on deploy point whilst getting taken over (Conquest)

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#81]
Hello.

### Current situation
On any conquest game, bots respawn directly around any deploy-point (Eg. point A, point B). However, whenever this point is being taken over, they spawn on that point. This allows the enemies to spawn-kill these bots.

### Difference between player spawning
When a player spawns on a deploy point which is being taken over, they do not spawn in the sight of the enemy but instead further away from the spawn point.

### Enhancement requested
It'd be extremely nice to see bots respawn outside the sight of enemy players for deploy points when respawning.

### Possible implementation
Raycasts around any respawning bot will cause performance issues.

This issue will be updated once I've gathered new elements.

**Comment by FlashHit** [comment]
there is a setting to use another spawnmethod which will spawn the bots on the vanilla spawnpoints. But someone needs to record the paths for them. I think atm only grand bazaar with the Bflag mod is supported.
With that solution bots will spawn like normal players.

**Comment by Joe91** [comment]
There is also a 2nd solution. On some maps there are separated spawn paths (for example Strike at Karkhand, Metro.)
As soon as they are recoded, the bots will use them. Since they are really easy to record anyone is welcome to add them to existing maps ;-)
