### ISSUE TITLE
[Bug] (Traces) Black waypoints are still visible after removing them 

### ISSUE THREAD

**Issue by Firjens** [Joe91/fun-bots#82]
When removing a waypoint, there are still black dots left on the ground, this is purely a visual bug and does not affect tracing at all. Saving the trace and loading it again will remove them.

![image](https://user-images.githubusercontent.com/57008952/124143527-7c8f2f80-da8b-11eb-8f53-940444f839b8.png)

This is a visual bug (confirmed by @Joe91 )

**Comment by MajorVictory** [comment]
This is intended behavior.
The black dots are orphaned nodes and get cleaned out on a save/load cycle.
They are left in place so that they can still be interacted with in case of accidental removal.
