### ISSUE TITLE
Option to disable GUI

### ISSUE THREAD

**Issue by SmartShots** [Joe91/fun-bots#9]
Is there any chance you could add an option in the config.lua to disable the in game GUI?

For my needs I don't need to use the GUI, I can set up what I want from the config.lua file. Being able to disable the GUI would then remove any possible access to changes by other players.

**Comment by Joe91** [comment]
You could just set a long and secure password in the Config File.
Or remove the key binding on F12.
Then noone can Open the menu. But we can implement this in the next vrrsion.

**Comment by Bizarrus** [comment]
Joe, if you need, i can implement these tomorrow.

i think, its fast and easy without some problems.

**Comment by SmartShots** [comment]
> You could just set a long and secure password in the Config File.
> Or remove the key binding on F12.
> Then noone can Open the menu. But we can implement this in the next vrrsion.

I removed the F12 binding. I'm happy just to do that if you don't want to add the config setting.

**Comment by Bizarrus** [comment]
Only removing the binding is bad. You can trigger some events to get an open door, you can bring the VU-Client to an debugging mode to do these things.

I will create this option tomorrow to disable the complete UI.
